### ISSUE TITLE
[rc5] Bootstrap cssFile not working

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-angular#432] opened 2016-09-02 19:25 UTC
When setting `cssFile` in the `platformNativeScriptDynamic` method, it does nothing.

Source:
```typescript
platformNativeScriptDynamic({
	bootInExistingPage: false,
	cssFile: 'styles/app.styles.css',
	startPageActionBarHidden: false,
}).bootstrapModule(AppComponentModule)
```
No warnings or errors displayed.

package.json
```json
"dependencies": {
	"@angular/core": "2.0.0-rc.5",
	"@angular/common": "2.0.0-rc.5",
	"@angular/compiler": "2.0.0-rc.5",
	"@angular/http": "2.0.0-rc.5",
	"@angular/platform-browser": "2.0.0-rc.5",
	"@angular/platform-browser-dynamic": "2.0.0-rc.5",
	"@angular/platform-server": "2.0.0-rc.5",
	"@angular/router": "3.0.0-rc.1",
	"@angular/forms": "0.3.0",
	"nativescript-angular": "0.4.0",
	"tns-core-modules": "2.2.1",
	"rxjs": "5.0.0-beta.6",
	"zone.js": "^0.6.12",
},
"devDependencies": {
	"babel-traverse": "6.15.0",
	"babel-types": "6.15.0",
	"babylon": "6.9.1",
	"lazy": "1.0.11",
	"nativescript-dev-typescript": "^0.3.2",
	"typescript": "^1.8.10"
}
```

**Comment by nsndeck** [comment] 2016-10-07 11:23
I've just tried it with the latest version and everything works as expected. So I'll close the issue.
Reopen if the problem is still existing.

**Closed by nsndeck** 2016-10-07 11:23 UTC

**Comment by dxshindeo** [comment] 2016-10-25 11:51
Hmm I'm seeing the same issue, and I have everything updated...

```
{
  "//": "npm-check-updates - use that package/command to check for available upgrades for the packages",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.PandaCab",
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/router": "3.1.1",
    "nativescript-angular": "1.1.1",
    "nativescript-geolocation": "0.0.13",
    "nativescript-google-maps-sdk": "^1.3.14",
    "nativescript-google-places": "0.0.3",
    "reflect-metadata": "^0.1.8",
    "tns-core-modules": "2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.3",
    "zone.js": "^0.6.21"
  }
}
```

**Comment by sarojrout** [comment] 2017-04-30 02:23
For me also, its not working. The bootstrap classes are not reflecting when running in IOS.
for example <Button text="Enter" class="btn btn-primary"></Button> not reflecting
