### ISSUE TITLE
IOS textfield goes to top on second time we focus on it 

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1705] opened 2019-01-27 20:10 UTC
**Environment**
```

 {
    "nativescript": {
        "id": "org.nativescript.hivekumobilenativescript",
        "tns-android": {
            "version": "5.1.0"
        },
        "tns-ios": {
            "version": "5.1.1"
        }
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "scripts": {
        "lint": "tslint \"src/**/*.ts\""
    },
    "dependencies": {
        "@angular/animations": "~7.0.0",
        "@angular/common": "~7.0.0",
        "@angular/compiler": "~7.0.0",
        "@angular/core": "~7.0.0",
        "@angular/forms": "~7.0.0",
        "@angular/http": "~7.0.0",
        "@angular/platform-browser": "~7.0.0",
        "@angular/platform-browser-dynamic": "~7.0.0",
        "@angular/router": "~7.0.0",
        "nativescript-angular": "~7.0.0",
        "nativescript-iqkeyboardmanager": "^1.3.0",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-listview": "^5.1.1",
        "nativescript-ui-sidedrawer": "~5.0.0",
        "reflect-metadata": "~0.1.10",
        "rxjs": "~6.3.0",
        "tns-core-modules": "~5.0.2",
        "zone.js": "~0.8.18"
    },
    "devDependencies": {
        "@nativescript/schematics": "~0.4.0",
        "codelyzer": "~4.5.0",
        "nativescript-dev-sass": "~1.6.0",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "~0.18.0",
        "tslint": "~5.11.0",
        "@angular/compiler-cli": "~7.1.0",
        "@ngtools/webpack": "~7.1.0"
    },
    "readme": "NativeScript Application"
}

```
**Describe the bug**

**To Reproduce**

```
<StackLayout>
  <ScrollView #scrollview height="90%">
  </ScrollView>

  <GridLayout height="10%">
    <TextField #textfield backgroundColor="red" verticalAlignment="bottom" class="chatTextField" row="0" col="0"
      [(ngModel)]="message"></TextField>
  </GridLayout>
</StackLayout>
```

> hear is the sample video 

`https://youtu.be/N0yevuwTDKY`
> if you want something else please tell .

**Comment by simonettoa** [comment] 2019-03-15 07:57
hey guys @tahir-jamil @NickIliev , any news on this?

**Comment by NickIliev** [comment] 2019-03-15 08:26
@tahir-jamil @simonettoa I am not able to reproduce the issue while using the latest tns-core-modules.

Here is [a Playground demonstration ](https://play.nativescript.org/?template=play-ng&id=aOEckq)- please do let me know if I am missing something

**Comment by simonettoa** [comment] 2019-03-15 10:32
@NickIliev I resolved changing the layout thanks to @gogoout from this page below:

[https://github.com/tjvantoll/nativescript-IQKeyboardManager/issues/42](url)

Thanks for your quick reply

**Comment by NickIliev** [comment] 2019-03-15 10:47
@tahir-jamil please do let me know if you are still experiencing this one and check the Playground to see if there are changes that have to be made to make this issue reproducible. 

Closing the issue, but I will reopen this one if the solution used by @simonettoa  is still not working for you.

**Closed by NickIliev** 2019-03-15 10:47 UTC
Labels: os: ios

**Comment by tahir-jamil** [comment] 2019-03-15 10:53
Hey gyes @Nickllive  @simonettoa
I have fround the fix

It happened when we use text field in side drawer on the root

So i just place a gridLayout around the side drawer and its fixed

**Comment by hhanckes** [comment] 2019-09-07 01:30
Hi guys, I am having the same issue, tried different approaches changing layout but nothing seems to do the trick. Any help is greatly appreciated!

This is what is happening:

![Ameiz2](https://user-images.githubusercontent.com/1490884/64468023-58f83980-d0ed-11e9-9437-54e3f48ff6b6.gif)

The template is the following (using nativescript-vue):

`
<template>
  <Page class="page">
      <GridLayout rows="auto, *, auto" class="m-y-10 m-x-10" height="100%">
        <GridLayout row="0" columns="*, auto">
          <Label col="0" class="h3 heading" textWrap="true" :text="'XXXX" fontWeight="bold"></Label>
          <Label col="1" class="p-t-5" text="Close" @tap="onCancelTap" />
        </GridLayout>
        <ListView row="1" for="msg in messages" ref="listView" @itemLoading="onItemLoading">
          <v-template>
            <GridLayout columns="*" rows="auto, auto" class="msg p-10">
              .....
            </GridLayout>
          </v-template>
        </ListView>
        <StackLayout row="2">
            <GridLayout columns="*, auto" class="m-10 form">
                <TextField class="text-input p-x-5" col="0" v-model="message" />
                <Button class="btn-primary p-10 m-x-10" col="1" text="Enviar" @tap="chat(message)"></Button>
            </GridLayout>
        </StackLayout>
      </GridLayout>
  </Page>
</template>
`
