### ISSUE TITLE
Whenever a modal-dialog is closed, the header-footer stops showing 

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1554] opened 2018-10-11 07:14 UTC
_From @nikeshjain on October 11, 2018 6:6_

Hello,

We have recently upgraded our app to NativeScript v4.2 with Angular v6. Earlier we were using NativeScript v3.3 with Angular v4. The app has a common header and footer section for navigating through the app. The central area of the app loads different components as per the current menu selection.

We have used "RadSideDrawer" control of the "nativescript-ui-sidedrawer" module in the app.component.html.

The "DrawerContent" contains the UI elements for user preferences that we need to show in the drawer when the user swipes down from the header
The "Maincontent" contains the UI elements for header, footer and the central area. The central area is kept in the page-router-outlet.

The navigation from the header-footer and the slider swiping features are working fine until we open and close a modal-dialog. Whenever a modal-dialog is closed, the header-footer stops showing, only the elements inside page-router-outlet continue to show.

The above issue is faced only in iOS. In Android, everything is working fine. In iOS, the issues started to arise after we upgraded to NS 4.2.

I have attached the demo code for your reference.
https://play.nativescript.org/?template=play-ng&id=EcYrUw&v=2

An urgent help in solving this issue will be greatly appreciated!

Thanks in anticipation!
Regards,
Nikesh Jain

_Copied from original issue: NativeScript/NativeScript#6383_

**Comment by NickIliev** [comment] 2018-10-11 07:14
@nikeshjain I can confirm that indeed the issue exists marking this one as a bug. We will investigate the case and post any related information here.

**Comment by NickIliev** [comment] 2018-10-11 07:14
Related to [https://github.com/NativeScript/nativescript-angular/issues/1532](https://github.com/NativeScript/nativescript-angular/issues/1532)

**Comment by nikeshjain** [comment] 2018-10-19 09:38
Hello NickIliev,

Any news on this?

Thanks in anticipation!
Regards,
Nikesh Jain

**Comment by tsonevn** [comment] 2018-11-28 09:09
Hi @nikeshjain,
I have tested the described scenario with the latest NativeScript(version 5.0), and it seems that the issue is resolved. You can check our upgrade instructions [here](https://docs.nativescript.org/releases/upgrade-instructions). In my opinion, we can close the issue. Please let me know if you are experiencing any further problem with the described case after the upgrade.

**Closed by tsonevn** 2018-11-28 09:09 UTC
Labels: bug, os: ios

**Comment by nikeshjain** [comment] 2018-12-10 13:30
Hi @tsonevn 
We tested the scenario with the latest NativeScript(version 5.0), and yes issue is solved now 
Thank you
