### ISSUE TITLE
how to set 'Page' level properties in angular component

### ISSUE THREAD

**Issue by BenevidesLecontes** [NativeScript/nativescript-angular#362] opened 2016-07-21 17:40 UTC
Hi! i'm using angular2-seed-advanced, web + mobile with angular+nativescript, i'm trying to set my background sitting under statusbar using opaqueTokens, but somehow it don't work. My code:
Token.ts
```
import {OpaqueToken} from '@angular/core';
export const PAGE: OpaqueToken = new OpaqueToken('page');
```

App.ts
```
nativeScriptBootstrap(NSAppComponent, [
    provide(WindowService, {useClass: WindowNative}),
    provide(PAGE, {useClass: Page}),
    ModalNative,
    provide(HttpService, {useClass: NSHttpService}),
    provide(TranslateLoader, {
        useFactory: () => {
            return new TNSTranslateLoader('assets/i18n');
        }
    }),
    NS_APP_PROVIDERS,
    nsProvideRouter(routes, {enableTracing: false})
]);
```

myComponent.ts
```
constructor(@Inject (PAGE) private page:PAGE) {
        if (CoreConfigService.IS_MOBILE_NATIVE) {
            console.log(this.page.ios);
            this.page.actionBarHidden = true;
            this.page.backgroundSpanUnderStatusBar=true;
            this.page.backgroundImage = this.page.ios ? "res://bg_login.jpg" : "res://bg_login";
        }
    }
```

**Comment by NathanWalker** [comment] 2016-07-21 19:02
@vakrilov I had been chatting with @BenevidesLecontes but I am also unsure of how best to modify `Page` level properties in an angular component?  The `OpaqueToken` setup is just to allow it to work on web and {N}. so don't be confused by all that above ^. Bottom line: how best to modify `Page` props within angular components.

**Comment by vakrilov** [comment] 2016-07-22 07:49
I'm not sure if I understand the issue correctly so - correct me if, I'm wrong.

I'm assuming the problem is the code sharing between web and mobile - no Page in web projects.
In this case I would suggest extracting the mobile-specific code in a directive that is only used in the {N} part. You can inject `Page` directly there as the code will be executed only in {N} context. You won't need the token and you will have typing support for the `Page` type. 

**Note:** You can inject `Page` in any component/directive and it will be the page the component/directive will be displayed on.

**Comment by BenevidesLecontes** [comment] 2016-07-22 14:27
@vakrilov yes you're right, i'm using `<page-router-outlet></page-router-outlet>` to load my components, does the same thought apply to that case?

**Comment by vakrilov** [comment] 2016-07-22 18:15
For the actual markup - you will probably have different files for web/mobile as the markup will be different. That said - the error you are getting is not expected - can you share some repo code?

**Comment by NathanWalker** [comment] 2016-07-23 21:15
@vakrilov I think the actual issue has gotten clouded by some other things mentioned here. The real question is why this doesn't work:
```
import {Page} from 'ui/page';
...
constructor(private page:Page) {
            this.page.actionBarHidden = true;
            this.page.backgroundSpanUnderStatusBar=true;
            this.page.backgroundImage = this.page.ios ? "res://bg_login.jpg" : "res://bg_login";
    }
```
changing props on injected `Page` appear to have no effect?

**Comment by vakrilov** [comment] 2016-07-25 05:37
Indeed I missed that - will investigate.
Does this happen:

1. On the first page or after navigation
2. Android or ios

**Comment by NathanWalker** [comment] 2016-07-25 05:49
On both. iOS at least, haven't checked Android.

**Comment by vakrilov** [comment] 2016-07-25 10:37
I was unable to reproduce the behavior. [Here is how I tested](https://gist.github.com/vakrilov/67224fc1b0d96c1d84d6efd112b91afa) - the background is changed here as expected.

Can you share some code?

**Comment by NathanWalker** [comment] 2016-07-26 19:45
Thank you @vakrilov for taking the time to look. Let's close this and I'll look at this again with him.

**Closed** 2016-07-27 07:48 UTC

**Comment by NathanWalker** [comment] 2016-08-02 11:01
Just to conclude, turns out his issue was related to fact that when using an `OpaqueToken` to build a web/{N} shared codebase, one must provide the `PAGE` `OpaqueToken` in the correct way, for instance this works:
```
import {OpaqueToken} from '@angular/core';
export const PAGE: any = new OpaqueToken('page');
...
nativeScriptBootstrap(AppComponent, [
    provide(PAGE, {
        useFactory: () => {
            const frame = topmost();
            if (frame) {
                return frame.currentPage;
            } else {
                return null;
            }
        }
    })
]);

... then in a component which is also used on the web, one can do this:

@Component({
    selector: 'any-cmp',
    templateUrl: 'any.component.html'
})
export class AnyComponent {

    constructor(@Inject(PAGE) private page:any) {
        if (Config.IS_MOBILE_NATIVE()) {
            this.page.actionBarHidden = true;
            this.page.backgroundSpanUnderStatusBar = true;
            this.page.backgroundImage = 'res://bg_login';
        }
    }
```

Works wonderfully and ensures that it doesn't break the web 👍

**Comment by BenevidesLecontes** [comment] 2016-08-02 13:21
That save me days!

**Comment by armackey** [comment] 2019-04-28 22:00
@NathanWalker 
This method looks good but I haven't been able to get this to work. Is provide a class I should import or create? Or has the standard changed?
