### ISSUE TITLE
Button background-color style issue

### ISSUE THREAD

**Issue by madsongr** [NativeScript/nativescript-angular#1037] opened 2017-10-11 21:24 UTC
Hi, I created a scss file to my login page and tried to change the button bg color to the same as the actionbar but the color got like the image below:

![image](https://user-images.githubusercontent.com/4735867/31467692-3ed1c248-aeb1-11e7-8fd1-4a0df1602d1a.png)

What´s happening?

**Comment by NickIliev** [comment] 2017-10-12 06:36
@madsongr this is [known issue](https://github.com/NativeScript/NativeScript/issues/3272) observed only on lower API levels on Android (API19 and below) and is caused by a native behavior where the transparency is applied by design. This issue is not observed when running the app on higher API levels.

To remove the default transparency you can apply [this workaround](https://github.com/NativeScript/NativeScript/issues/3272#issuecomment-266685465) (which would overwrite the ANdroid styling) but as a trade-off, it would remove the ripple effect (which can be applied with nativescript-ripple plugin)

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/3272#issuecomment-266685465](https://github.com/NativeScript/NativeScript/issues/3272#issuecomment-266685465)

**Closed by NickIliev** 2017-10-12 06:36 UTC
Labels: question

**Comment by madsongr** [comment] 2017-10-12 16:12
@Nicklliev it's the first time I see that. I have another app working perfectly.
But anyway, I'll try your suggestions.
