### ISSUE TITLE
Can`t start application on any device after tns was updated

### ISSUE THREAD

**Issue by casufi** [NativeScript/nativescript-angular#402] opened 2016-08-18 20:57 UTC
I am getting "Unfortunately, myappname has stopped"  when i try to debug my app on any Android devace (AVD Geanymotion)
http://pastebin.com/raw/edqzXR5R

**Comment by slavchev** [comment] 2016-08-22 09:02
Hi @casufi 

Currently we use a relatively old version of V8 which is known to have bugs in some RegEx/JIT scenarios. The good news is that we already prepared and tested [a branch with newer version](https://github.com/NativeScript/v8/tree/nativescript-5.2.361) which will be merged for the next release. Meanwhile I would suggest to find which RegEx cause the problem and try to refactor the code around.

**Comment by casufi** [comment] 2016-08-24 22:52
I tried ti build an empty project, that I created using tns create my-app-name --ng so I don`t know where I should check RegEx

**Comment by slavchev** [comment] 2016-08-25 08:49
There are regular expressions in our modules (`tns-core-modules`). If this is critical for you I would suggest to inspect [the code](https://github.com/NativeScript/NativeScript/search?utf8=%E2%9C%93&q=regex). Also, if you are able to reproduce it consistently on some device please report the exact device model. As for emulators maybe playing with the emulator setting (memory) would help to workaround the issue. Either way I will boost the priority of updating V8 to the latest version.

**Comment by hdeshev** [comment] 2016-09-21 10:49
Does this issue still exist with NS 2.3.0. Didn't we update V8?

**Comment by slavchev** [comment] 2016-09-21 10:59
@hdeshev In 2.3.0 we use the same V8 version as for 2.2.0. I guess the [new branch](https://github.com/NativeScript/android-runtime/tree/plamen5kov/refactored_5.2.361) will be merged next week.

**Comment by NickIliev** [comment] 2018-01-02 13:10
The issue is not reproducible with the latest NativeScript

**Closed by NickIliev** 2018-01-02 13:10 UTC
