### ISSUE TITLE
APP_INITIALIZER doesn't allow navigation in "nativescript-angular": "^6.1.0" version

### ISSUE THREAD

**Issue by Disha-Modi** [NativeScript/nativescript-angular#1493] opened 2018-08-22 13:19 UTC
Hello,

In our app, we check whether the user is already logged in or not on App Startup. If the user is already logged in, then we redirect him to the Dashboard screen of our app, otherwise we redirect him to the login screen. We used to perform this check in APP_INITIALIZER.

But after upgrading to NativeScript v4.2 and NativeScript-Angular v6.1.0, the redirection to a correct screen has stopped working using APP_INITIALIZER. It simply shows a white screen. The sample code can be found on the following URL:
https://play.nativescript.org/?template=play-ng&id=Z16l6O&v=6

Can you please check and let us know whether the latest version supports navigation using APP_INITIALIZER or not? If not, then which alternative should we use to redirect the user to an appropriate screen after app startup?

Thanks in anticipation...
Regards,
Disha.

**Comment by tsonevn** [comment] 2018-08-22 14:19
Duplicate of https://github.com/NativeScript/nativescript-angular/issues/1487

**Closed by tsonevn** 2018-08-22 14:19 UTC
