### ISSUE TITLE
iosOverflowSafeArea applied to all creates unscrollable offset

### ISSUE THREAD

**Issue by cremfert** [NativeScript/nativescript-angular#1646] opened 2018-12-04 13:26 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1-2018-11-08-12560
 - Cross-platform modules: 5.0.2
 - iOS Runtime: 5.0.1-rc-2018-11-15-163743-01
 - Plugin(s):
 - NativeScript-Angular: 5.0.2
 - Angular: 6
 
**Describe the bug**
This is my code:
```
<StackLayout row="0" column="0" width="100%" height="100%" class="wallpaper">
            <ScrollView #messagesView id="messagesView">
              <StackLayout id="stackLayout" style="padding-bottom: 10; padding-top: 50;" id="stackLayout">
                <StackLayout *ngFor="let message of messages" iosOverflowSafeArea="false">
                    <Label *ngIf="sentByMe(message)" [text]="message[2]" horizontalAlignment="right" textWrap="true" style="margin-left: 30%; margin-top: 10; margin-right: 10; padding: 5; background-color: #11a1ce; color: white;"></Label>
                    <Label *ngIf="sentByMe(message)" [text]="message[3] | date: 'dd.MM.yy HH:mm'" horizontalAlignment="right" textWrap="true" style="margin-left: 30%; margin-right: 10; padding: 5; background-color: transparent; color: #666; font-size: 10px;"></Label>
                    <Label *ngIf="!sentByMe(message)" [text]="message[2]" horizontalAlignment="left" textWrap="true" style="margin-right: 30%; margin-top: 10; margin-left: 10; padding: 5; background-color: white;"></Label>
                    <Label *ngIf="!sentByMe(message)" [text]="message[3] | date: 'dd.MM.yy HH:mm'" horizontalAlignment="left" textWrap="true" style="margin-right: 30%; margin-left: 10; padding: 5; background-color: transparent; color: #666; font-size: 10px;"></Label>
                </StackLayout>
              </StackLayout>
            </ScrollView>
      </StackLayout>
```
As soon as I add ```iosOverflowSafeArea="false"``` also to the first StackLayout (as recommended due to bug #1593), the last elements are below the scrollable area and can only be seen when the area is "overscrolled" (bounce effect). What is the appropriate way?

**To Reproduce**
See code above.

**Expected behavior**
All entries in a ScrollView/StackLayout should be visible and ```*ngFor``` should be working as expected (although this is discussed in #1593).

**Comment by NickIliev** [comment] 2018-12-04 14:02
@cremfert the issue seems like a duplicate of [the linked one ](https://github.com/NativeScript/nativescript-angular/issues/1593). Can you please post [a Playground demo](https://play.nativescript.org/) demonstrating your exact problem so we could investigate further.

**Closed as completed** 2018-12-11 13:55 UTC
Labels: os: ios, needs more info
