### ISSUE TITLE
http Response.text() behaves differently from Android and iOS

### ISSUE THREAD

**Issue by marco-gagliardi** [NativeScript/nativescript-angular#918] opened 2017-07-28 16:05 UTC
the following code to get and RSS stream

```
this.http.get(Config.avvisiURL)
            .map(res => res.text())
            .subscribe(res => {
                console.log(res);
                let doc = XmlObjects.parse(res);
                ...
```
works fine on Android (the XML document is correctly parsed), but on iOS the console logs:

`<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d227574 662d3822 3f3e0a3c...`

Any idea of what is going on?

**Comment by spike1292** [comment] 2017-08-08 12:13
looks the same like https://github.com/NativeScript/NativeScript/issues/4514

**Comment by tsonevn** [comment] 2017-08-09 10:19
Hi @marco-gagliardi,
Indeed this issue seems to be related to [#4514](https://github.com/NativeScript/NativeScript/issues/4514), which is already fixed with `tns-core-modules` version 3.1.1. Could you upgrade your `tns-core-modules` to version `3.1.1` in your `package.json` file and to verify whether you will have the same problem .

Bear in mind to delete node_modules and platforms folders, before rebuilding the app.

**Comment by tbsf** [comment] 2017-10-06 23:18
I'm having this issue and have tns-core-modules 3.2.0

**Comment by tsonevn** [comment] 2017-10-09 12:06
Hi @tbsf,
Could you provide some more info about the problem and for your environment(CLI, node, npm versions) and whether you are building the project for iOS or Android? 
I tested the described scenario while using [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/http/http-get), however, was unable to recreate the problem. 
It will also help if you could provide sample project, which could be debugged locally.

**Comment by tbsf** [comment] 2017-10-09 16:08
@tsonevn This issue only happens on iOS and seems to only happen for endpoints that use gzip for the content-encoding.

nativescript-cli: 3.2.1
node: 8.2.1
npm: 5.3.0

Please let me know if any other information would be helpful.

**Comment by tsonevn** [comment] 2017-10-10 12:56
Hi @tbsf ,
 I  created a sample project, could you review it and make the needed changes, which will allow us to reproduce the issue.

Thank you in advance for your cooperation
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1371930/Archive.zip)

**Comment by tbsf** [comment] 2017-10-10 18:18
@tsonevn I have isolated the issue to the Content-Type being returned. The Content-Type is set as "application/x-JavaScript". I changed this Content-Type to return as "application/json" and response.text() worked correctly. Any ideas why this Content-Type is not working? I would think it should still return text.

**Comment by tsonevn** [comment] 2017-10-11 08:29
Hi @tbsf ,

Also tested the scenario, while changing the ` Content-Type` to `application/x-JavaScript`, however as you could see in the attached GIF I am unable to recreate the problem.  I tested the project on iOS 10.3 and 11. To verify, what is causing the issue, please provide the project, which you are using on your side. At this time I could not confirm if there is a real issue while changing the  ` Content-Type`
![screencast 2017-10-11 at 11 20 15 am](https://user-images.githubusercontent.com/17448734/31429669-54694f52-ae77-11e7-8dbf-3c13967a96a2.gif)

**Comment by tbsf** [comment] 2017-10-11 13:10
@tsonevn it looks like you are sending the content type in the request header. This issue occurs when the response content-type is set to application/x-javascript. I will try to set up the example project if I can find a way to set the response content type.

**Comment by airandfingers** [comment] 2017-11-03 19:09
Hi @tsonevn, I've reproduced this as @tbsf described, by changing Archive/app/item/http-get.services.ts to point to http://yourjavascript.com/1101745171/test.js, a simple JSON file that's served with the response header "Content-Type: text/javascript; charset: UTF-8". (I also had to set NSAllowsArbitraryLoads in Info.plist, since that file is served via HTTP, and I modified the logging to test both res.text and res.json.)

![javascript-content-type-error](https://user-images.githubusercontent.com/1088051/32391530-b024824c-c08f-11e7-990a-98fecdbe697c.gif)

The logs at the end are:

```
CONSOLE LOG file:///app/item/http-get.services.js:14:20: getData
CONSOLE LOG file:///app/item/http-get.services.js:18:24: res.headers is [object Object]
CONSOLE LOG file:///app/item/http-get.services.js:19:24: res.text() is <7b227465 7374223a 3132332c 22746573 74696e67 223a7472 75657d>
CONSOLE ERROR file:///app/item/http-get.services.js:24:30: SyntaxError: JSON Parse error: Unrecognized token '<'
```

Is the fix as simple as adding text/javascript to tns-core-modules/xhr/xhr.js, as shown in https://github.com/NativeScript/NativeScript/pull/4531/files?

**Comment by tsonevn** [comment] 2017-11-07 12:25
Hi @airandfingers,
Thank you for the provided guidelines for reproducing. 
I tested it on my side and was able to recreate the issue on my side. However, the suggested fix seems to not be applicable in this case. I am attaching sample project, which could be used for debugging. 
For further info, please keep track on the issue.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1449931/Archive.zip)

**Comment by NickIliev** [comment] 2019-04-15 12:13
Closing the issue. For all interested in the case, please use the `HttpClient` (and not the old http module)

**Closed by NickIliev** 2019-04-15 12:13 UTC
Labels: bug, http
