### ISSUE TITLE
Using Http with map to get json response doesn't seem to work

### ISSUE THREAD

**Issue by eesdil** [NativeScript/nativescript-angular#38] opened 2016-01-21 08:03 UTC
Trying to use http module from angular2 in nativescript, but I am getting this error:

    file:///app/tns_modules/angular2/src/platform/serv
    er/parse5_adapter.js:55:75: EXCEPTION: TypeError: _this.http.request(address, options)
                                .map is not a function. (In '_this.http.request(address, options)

This is working in the browser and also including in both places the rxjs map module

    import 'rxjs/add/operator/map';

If I remove this from the browser I am getting the same message. But with nativescript even if I add it, it doesnt work...

What can be wrong here? Is there any working example using the http module?

Posted here, but so far no ideas, so adding it here as well

http://stackoverflow.com/questions/34899835/using-map-in-nativescript-with-angular2

**Comment by hdeshev** [comment] 2016-01-21 14:42
@eesdil, I had an early experiment with the http module, but then the API changed and I never updated it.

What example are you trying to port from the browser version? Could you post a repro project that I can run locally?

**Comment by eesdil** [comment] 2016-01-21 14:45
Thanks. It Would be too complicated to share and use it probably.  I will create a repo bit later to be able to check it.

**Comment by eesdil** [comment] 2016-01-21 17:51
Hmm. I created one, but yet there is no backend to connect and it doesn't start :)... but you can see the code at least for now. 
https://github.com/eesdil/test_mobile

**Comment by hdeshev** [comment] 2016-01-22 14:36
I got it running [here](https://github.com/hdeshev/test_mobile/commit/200a541095d7b94c1d10812a67b06d0f3f4c2331). I had to add the typescript hooks and some of the compat `d.ts` files (the commit before that), but nothing more. I wonder if the problem occurs just for certain types of requests or parameters.

**Comment by eesdil** [comment] 2016-01-22 16:13
Thank you. I am checking it. It can happen that I am not getting back result (wrong ip address, as localhost cannot be accessed in the emulator), thats why it fails. But I am getting a bit frustrated as it takes 10 minutes to start the debugger. And Without debugger I just get immediate crash.

**Comment by eesdil** [comment] 2016-01-23 14:28
With the default android emulator it is a nightmare..., but using the genymotion it is working pretty well. So the http (map, etc) working fine in android, tried in linux and osx. 

But in ios emulator I have the same error using the same code:

```
.js:79:28: JS ERROR EXCEPTION: Error during evaluation of "tap"
        ORIGINAL EXCEPTION: TypeError: this.http.request(address)
                    .map is not a function. (In 'this.http.request(address)
                    .map(function (res) { return res.json(); })', 'this.http.request(address)
                    .map' is undefined)
```

**Comment by eesdil** [comment] 2016-01-24 09:31
Didnt write yesterday, but even this is working in android, in the subscribe function I am getting string instead of json. Strangely if I remove the map function, I am not getting the result (just the headers) in the subscribe function.

**Comment by hdeshev** [comment] 2016-01-26 13:34
This looks like a bug in the iOS `require` implementation. I'll update this issue when I know more.

**Comment by vakrilov** [comment] 2016-03-21 13:45
@eesdil 
Can you please confirm that the issue is resolved with the latest(0.0.36) release of nativescript-angular. 
I have tested it with the [sample-ng-http](https://github.com/NativeScript/sample-ng-http/tree/master/mobile) project and everything seems to work fine.

**Comment by eesdil** [comment] 2016-03-21 13:47
Thanks. I will check it and let you know.

**Comment by vakrilov** [comment] 2016-03-24 16:09
@eesdil I'm closing the issue - please reopen it if the problem reoccurs.

**Closed by vakrilov** 2016-03-24 16:09 UTC

**Comment by eesdil** [comment] 2016-04-03 11:41
It seems it is working fine in the sample-ng-http project, but not in mine... But at least it means it can work, just have to find the reason. thanks anyway

**Comment by shangab** [comment] 2016-09-21 15:44
I tried to get an Http request as the following too, in one of my components:

`import {Component, OnInit} from "@angular/core";
import {Http} from "@angular/http";
import "rxjs/Rx";

@Component({
    selector:"list",
    providers:[Http],
    template:`
        <StackLayout> 
            <Label text="I am The list"></Label>
            <Button text="GO TO LOGIN" [nsRouterLink]="['/login']"></Button>
            <StackLayout>
                <Label text="I am The list"></Label>
            </StackLayout>
        </StackLayout>  
    `
})
export class ListComponent implements OnInit{
    private _data;

    constructor(private _http:Http){
        
    }
    ngOnInit(){
        this._http.get("[URL to get the Json data]").map(res=> res.json()).subscribe(res=> this._data=res);
        console.log(this._data[0].name);
    }
}`

But I get the following error:

Error: Uncaught (in promise): Error: Error in ./ListComponent class ListComponent_Host - inline template:0:0 caused by: No provider for ConnectionBackend!
