### ISSUE TITLE
Error: Command ./gradlew failed with exit code 1 Error output: 

### ISSUE THREAD

**Issue by zeesulehria** [NativeScript/nativescript-angular#1413] opened 2018-07-03 19:01 UTC
```
Unable to apply changes on device: UKYTWOVGTG69RK55. Error is: Failed to build plugin nativescript-ng-shadow : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/m.tahir/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
my package.json is

```

// Add your native dependencies here:

// Uncomment to add recyclerview-v7 dependency
//dependencies {
//	compile 'com.android.support:recyclerview-v7:+'
//}

dependencies {
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                details.useVersion '26.0.+'
            }
        }
    }
}

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "com.hiregoat.app"  

    renderscriptTargetApi 25
    renderscriptSupportModeEnabled true
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
  

} 

def settingsGradlePath

if(project.hasProperty("appResourcesPath")){
    settingsGradlePath = "$project.appResourcesPath/Android/settings.gradle";
} else {
    settingsGradlePath = "$rootDir/../../app/App_Resources/Android/settings.gradle";
}

def settingsGradleFile = new File(settingsGradlePath);

if(settingsGradleFile.exists())
{
    apply from: settingsGradleFile;
}

```

**Comment by tsonevn** [comment] 2018-07-04 05:49
Duplicate of #1412

**Closed by tsonevn** 2018-07-04 05:49 UTC

**Comment by ixhimanshu** [comment] 2020-01-21 10:35
This usually happens because of the incompatible java JDK version. Please check your current java version using this command: **java --version**

If there is java installed already then remove that version first, after that install LTS version of java JDK from [https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)
