### ISSUE TITLE
White Screen after splash screen and before main screen 

### ISSUE THREAD

**Issue by Udobnaja** [NativeScript/nativescript-angular#1089] opened 2017-11-15 08:48 UTC
After Splash screen and before main screen (route), i see white screen + ActionBar with default app_name (that i set in folder "App_Resources/Android/values/strings.xml").

![android](https://user-images.githubusercontent.com/8513713/32826412-ef58b05e-c9f0-11e7-8edc-fda3ecdaf23b.gif)

Platform: Android
```
 "dependencies": {
    "@angular/animations": "~4.4.5",
    "@angular/common": "~4.4.5",
    "@angular/compiler": "~4.4.5",
    "@angular/core": "~4.4.5",
    "@angular/forms": "~4.4.5",
    "@angular/http": "~4.4.5",
    "@angular/platform-browser": "~4.4.5",
    "@angular/platform-browser-dynamic": "~4.4.5",
    "@angular/router": "~4.4.5",
    "@ngrx/effects": "^4.0.5",
    "@ngrx/store": "^4.0.3",
    "nativescript-android-utils": "^1.0.2",
    "nativescript-angular": "~4.4.1",
    "nativescript-appversion": "^1.4.1",
    "nativescript-cardview": "^2.0.2",
    "nativescript-geolocation": "^4.2.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.3",
    "tns-core-modules": "^3.3.0",
    "zone.js": "^0.8.16"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.4.5",
    "@ngtools/webpack": "~1.6.0",
    "@types/lodash": "^4.14.70",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tslint": "^4.5.1",
    "typescript": "~2.3.4",
    "uglifyjs-webpack-plugin": "^1.0.0",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
```

You can find all code here 
https://github.com/Udobnaja/nativescript-taxi
In my routings files i have no blank components

this behavior was before i start using webpack or separate app module to features modules, so it was from the start i guess

Maybe you know why it can happen? or how resolve it

**Comment by btaluy** [comment] 2018-01-31 07:47
What I see in your routing is that you redirect to /card.

in app.routing.ts this is how i use it

export const routes = [
  {
    path: '',
    loadChildren: 'your card module'
  }
];

**Comment by NickIliev** [comment] 2019-01-08 14:32
Closing this one as I am not able to reproduce the issue while using the latest version of nativescript-angular.

**Closed by NickIliev** 2019-01-08 14:32 UTC

**Comment by yatinkapur** [comment] 2020-02-13 09:21
@NickIliev I am facing same issue with Nativescript@5.4.2 with angular

**Comment by NickIliev** [comment] 2020-02-13 12:21
@yatinkapur the issue on my side was entirely related to working with HMR - it is not happening in production or when the HMR is not used (`--no-hmr`)  or when the `--release` flag is used (in release the HMR is turned off by design). Test with app build in production and let me know if you are still experiencing this one.

**Comment by Meyer-dev** [comment] 2020-02-13 12:59
I am experiencing the same issue. Even with a release build. Does the
splash screen only route once the app has its initial view rendered? This
will be helpful as I would prefer the app to remain on the splash screen as
apposed to route to what appears an empty/not fully rendered screen. Any
help is much appreciated.

**Comment by yatinkapur** [comment] 2020-02-14 06:26
@NickIliev I have released an app with --release flag and still have this issue in the production build.

**Comment by NickIliev** [comment] 2020-02-17 09:45
@Meyer-dev @yatinkapur can you guys provide a sample project that reproduces the issue?
