### ISSUE TITLE
[formControl] binding not working on Switch element

### ISSUE THREAD

**Issue by chrillewoodz** [NativeScript/nativescript-angular#1624] opened 2018-11-21 15:04 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - NativeScript-Angular: 6.1.0
 - Angular: 6.1.10
 
**Describe the bug**
`Switch` doesn't appear to support binding `formControl` to it as it doesn't set the default value of `true`, as well as it doesn't respond to changes to the value. It does however change the `checked` attribute.

I looked here and you said you had implemented this, although you only show an example with `ngModel`: https://github.com/NativeScript/nativescript-angular/issues/72

**To Reproduce**

Add the `NativeScriptFormsModule` and `ReactiveFormsModule` to `AppModule`:

@NgModule({
  imports: [
    NativeScriptModule,
    NativeScriptFormsModule,
    ReactiveFormsModule,
    AppRoutingModule
  ],
  exports: [
    NativeScriptModule
  ],
  declarations: [
    AppComponent
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})

export class AppModule {}

Then create a form using `FormBuilder`:

```
public form = this.fb.group({
    ongoing: this.fb.group({
      checked: [true]
    })
  });
```

Then try to bind the `formControl` to the `Switch`:

`<Switch class="ongoing" [formControl]="form.get('ongoing.checked')"></Switch>`

You will see that the value is still `false` and if you listen to `valueChanges` it doesn't emit when you change the value.

**Expected behavior**
I expect the `formControl` value to be bound to the `checked` state when binding `formControl` to it.

**Comment by tsonevn** [comment] 2018-11-22 08:02
Duplicate of https://github.com/NativeScript/nativescript-angular/issues/1362

**Closed by tsonevn** 2018-11-22 08:02 UTC
