### ISSUE TITLE
(ui/dialog): Sort order of Dialog Buttons

### ISSUE THREAD

**Issue by artdias90** [NativeScript/nativescript-angular#1355] opened 2018-05-31 14:42 UTC
I'm using a Dialog with `ok / cancel / neutral` options, and it seems like I can't decide which button goes where? 

https://play.nativescript.org/?template=play-ng&id=pY5Tta

You can see in [documentation](https://docs.nativescript.org/ui/dialogs#confirm) the problem as well.

**Comment by tsonevn** [comment] 2018-06-01 13:18
Duplicate of [#5896](https://github.com/NativeScript/NativeScript/issues/5896)

**Closed by tsonevn** 2018-06-01 13:18 UTC
