### ISSUE TITLE
Service exited due to signal: Killed: 9

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-angular#101] opened 2016-03-04 14:58 UTC
NativeScript Version: 1.6.1

I'm unable to use Angular 2 with NativeScript at the moment. I'm using the [`template-hello-world-ng` project](https://github.com/NativeScript/template-hello-world-ng).

The error I get isn't terribly helpful....

````bash
Project successfully built.
Using  /Users/burkeholland/dev/burkeholland/my-app-name/platforms/ios/build/emulator/myappname.app
Starting iOS Simulator
Mar  4 08:15:53 --- last message repeated 1 time ---
Mar  4 08:15:53 hollandmac com.apple.CoreSimulator.SimDevice.FAE7B936-79CE-46C4-859F-65506A603837.launchd_sim[52478] (UIKitApplication:org.nativescript.myappname[0x71cd][52664]): Service exited due to signal: Killed: 9
````

Steps to recreate:

````shell
tns create my-app-name --template https://github.com/NativeScript/template-hello-world-ng

cd my-app-name && tns platform add ios

tns run ios --emulator
````

**Comment by burkeholland** [comment] 2016-03-04 15:33
Updating with possible related race condition error on iOS Simulator. Could be cause by app size.

https://forums.developer.apple.com/thread/25221

**Comment by rosen-vladimirov** [comment] 2016-03-04 15:35
It looks like there are some problems when deploying application to iOS Simulator related to project's size. Some information can be found here:
https://forums.developer.apple.com/thread/25221
As a workaround the following behavior can be used:
```
tns deploy ios --emulator --justlaunch
tns livesync ios --watch
```

**Comment by burkeholland** [comment] 2016-03-04 15:56
:+1:

**Comment by burkeholland** [comment] 2016-03-07 17:45
It appears to me that `livesync` is not syncing changes from the TypeScript. Changes their require me to run the `deploy` command all over again.

**Comment by aaweb** [comment] 2016-03-22 16:37
+1

**Comment by jlooper** [comment] 2016-04-04 15:02
I get this error consistently on iOS emulator when running Angular+{N} apps. It's a big workflow stopper for me :(

**Comment by tjvantoll** [comment] 2016-04-15 19:09
I’m going to open this up, because I know at least @burkeholland, @jlooper, and @sebawita are still having this issue, and I think we need to come up with some way to workaround the problem.

**Comment by tjvantoll** [comment] 2016-04-22 12:52
I can confirm that this issue is fixed when using Xcode 7.3 and version 2.0 of the {N} CLI, so I’m going to close this issue for now. If anyone hits this after upgrading to the soon-to-be-released 2.0 CLI please comment so we can look into this.

**Comment by jlooper** [comment] 2016-04-27 16:49
I do see this issue if using `tns emulate ios` or `tns run ios --emulator` with Xcode 7.3 and {N} 2.0. The workaround is to make sure Xcode is closed, reset the simulator (Simulator > Reset Content and Settings) and type:

1) Call `tns run ios --justlaunch` (Make sure you do not have any iOS devices attached.
2) Call `tns livesync ios --watch`

**Comment by georgeedwards** [comment] 2016-05-01 14:56
I also face the same issue using 2.0, XCode 7.3 and OSX El Capitan

**Comment by rdlauer** [comment] 2016-05-09 20:56
Same issue here with {N} 2.0 + Xcode 7.3.1. The `--justlaunch` flag is like magic, but far less convenient.

**Comment by khanhlu2013** [comment] 2016-05-13 01:44
This is a intermittent problem in my experience.

**Comment by cfjedimaster** [comment] 2016-06-02 18:41
I ran into this today. It took me about 10 relaunches or so for it to finally work. I'd seriously consider adding a note someplace in the docs for folks going through the tutorial.

**Comment by tjvantoll** [comment] 2016-06-03 13:39
Reopening this because clearly people are still hitting the problem.

**Comment by tjvantoll** [comment] 2016-06-03 14:18
@cfjedimaster Warning added in https://github.com/NativeScript/docs/commit/0aebd9861f59f0511598ad20f7775b7cfc34e5f4. Thanks for the feedback as always.

**Comment by dwehrmann** [comment] 2016-06-07 07:24
+1 also having this problem.
`tns run ios --emulator` exits with `Signal: Killed 9`

`tns run ios --justlaunch` works for me, but livesync doesn't. I think that's a real showstopper – does anybody have a workaround?

jlooper's advice doesn't work for me:
`Project successfully prepared
Executing before-livesync hook from /Users/SB3/www/mobile-dev/groceries/sample-Groceries/hooks/before-livesync/nativescript-angular-sync .js
Transferring project files...
Successfully transferred all project files.
Applying changes...
Successfully synced application org.nativescript.groceries on device A451650D-0FF3-4508-B5AB-7DB59D552076.
Executing before-watch hook from /Users/SB3/www/mobile-dev/groceries/sample-Groceries/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Jun  7 09:12:22 SB3 com.apple.CoreSimulator.SimDevice.A451650D-0FF3-4508-B5AB-7DB59D552076.launchd_sim[36659] (UIKitApplication:org.nativescript.groceries[0x6d43][77918]): Service exited due to signal: Killed: 9
`

**Comment by hdeshev** [comment] 2016-06-08 07:52
This issue was moved to NativeScript/nativescript-cli#1816

**Closed by hdeshev** 2016-06-08 07:52 UTC

**Comment by AssemT** [comment] 2016-07-07 05:29
I'm having the same problem, can anyone explain to me how to fix it? I have tried these commands:
1) Call tns run ios --justlaunch
2) Call tns livesync ios --watch
No progress, still says 'Service exited due to signal: Killed: 9'. I read that it may be memory leaks or too much time to launch the app. To be honest, it is taking too long to launch, but I don't know how to fix this issue. Thanks.

**Comment by wdulin** [comment] 2016-08-23 23:11
Followed the tutorial exactly having the same issue.

**Comment by berardo** [comment] 2016-11-15 08:04
Sorry for reheating this thread, but I'm still experiencing the same problem.
Trying `tns run ios --emulator` and also `tns run ios --justlaunch` + `tns livesync ios --watch`.
As some reported, it takes ages to spin up the emulator. Once it's done, I can only see the splashscreen and then it closes (due to Kill 9 signal). Just fyi, the app is that 16 taps counter.
Any news? It's been a long time without hearing back from anyone.
Thanks
