### ISSUE TITLE
AuthGuard not working.

### ISSUE THREAD

**Issue by praven07** [NativeScript/nativescript-angular#1517] opened 2018-09-14 16:21 UTC
I'm trying to use auth guard using caLoad on the routes. It does not work. I event tried using canActivate but still failed to work. I have attached a sample code below that I used.

I'm using
`
tns-core-modules: 4.2.0;
tns-ios: 4.2.0
`

```typescript
const routes: Routes = [
    { path: "", redirectTo: "/home", pathMatch: "full" },
    { path: "home", loadChildren: () => require("./home/home.component")["HomeModule"], canLoad: [AuthGuard]},
    { path: "calendar", loadChildren: () => require("./calendar/calendar.component")["CalendarModule"], canLoad: [AuthGuard]},
];
```

**Comment by NickIliev** [comment] 2018-09-17 10:50
@praven07  can you share a Playground that can demonstrate your issue? What is expected to happen on the default route with the above setup - isn't the guard meant only for the second `calendar` route (and not for the `home`)?

**Comment by praven07** [comment] 2018-09-17 15:23
So I found out what was causing the problem. In the auth guard I was returning an observable that says if the user if logged in or not. When I removed the observable and just added a return boolean it started to works.

I kinda wrote a sample app to show what I was trying to do.
[https://play.nativescript.org/?template=play-ng&id=fFO6fl](url)

**Comment by NickIliev** [comment] 2018-09-18 08:12
@praven07 the issue seems to be related to Angular known behavior logged in [https://github.com/angular/angular/issues/18991#issuecomment-326770757](https://github.com/angular/angular/issues/18991#issuecomment-326770757) , [https://github.com/angular/angular/issues/25262](https://github.com/angular/angular/issues/25262), and in [https://github.com/angular/angular/issues/10556](https://github.com/angular/angular/issues/10556)

CLosing as the issue is related to Angular.

**Closed by NickIliev** 2018-09-18 08:12 UTC
Labels: needs more info, question
