### ISSUE TITLE
Can anyone help me with this ?

### ISSUE THREAD

**Issue by bfmnigfh0608** [NativeScript/nativescript-angular#1622] opened 2018-11-21 04:26 UTC
![46507303_583499698777806_9203905406823301120_n](https://user-images.githubusercontent.com/45221675/48818980-ba326480-ed88-11e8-80cf-e3cb6ff24bab.png)

**Comment by tsonevn** [comment] 2018-11-21 07:18
Duplicate of https://github.com/NativeScript/NativeScript/issues/6591

**Closed by tsonevn** 2018-11-21 07:18 UTC
