### ISSUE TITLE
ListView disappear 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#587] opened 2016-12-12 07:07 UTC
_From @CodeXtinction on December 12, 2016 2:44_

hello, i have a issue with physical back button, when i select an element from the list to navigate to another view and then press back button the list disappears, the list loads on  ngOnInit and i get  an object from sqlite, but when the list view loads with back button it seems the object does not exist ,any idea why this happen?

Android
Nativescript + Angular 2 

![](http://k60.kn3.net/F/D/9/E/C/6/B35.png)

![](http://k60.kn3.net/8/D/C/E/5/C/47F.png)

_Copied from original issue: NativeScript/NativeScript#3278_

**Comment by tsonevn** [comment] 2016-12-12 07:07
Hi @CodeXtinction,
Thank you for contacting us, 

I reviewed your case, however was unable to reproduce such a problem. Could you send us some more info about your environment(`CLI`, `tns-core-modules`, `node versions`) and your problem. It would help also, if you could send us sample project, which could be debugged locally. For your convenience I am attaching [link ](https://github.com/tsonevn/NGRouterSample) to a sample project.

Hope this helps

**Comment by m-abs** [comment] 2016-12-13 11:12
It looks like the same problem I reported:
https://github.com/NativeScript/nativescript-angular/issues/572

I've written a simple example see this comment:
https://github.com/NativeScript/nativescript-angular/issues/572#issuecomment-264480760

We worked around the problem by moving the Item content to a separate component, see: https://github.com/NativeScript/nativescript-angular/issues/572#issuecomment-264694704

**Comment by hdeshev** [comment] 2016-12-13 14:12
Duplicate of #572

**Closed by hdeshev** 2016-12-13 14:12 UTC
Labels: T:Question

**Comment by CodeXtinction** [comment] 2016-12-15 16:58
@m-abs  thanks i'll check that :)
