### ISSUE TITLE
Not All Kabab Case Is Recognized

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-angular#168] opened 2016-04-11 20:28 UTC
Some elements are not recognized when kabab case.

**Environment**

OSX 10.11.1
NativeScript 1.7.0

**Steps To Reproduce**

Create a component with a `<stack-layout>` in kabab case. The StackLayout will be ignored. Use `<StackLayout>` and the app works as expected.

**Comment by hdeshev** [comment] 2016-04-12 09:54
Duplicate of #29

**Closed by hdeshev** 2016-04-12 09:54 UTC
