### ISSUE TITLE
tabLayout.getItemCount is not a function

### ISSUE THREAD

**Issue by codeback** [NativeScript/nativescript-angular#657] opened 2017-02-06 11:27 UTC
I'm facing this error 'tabLayout.getItemCount is not a function' after updating to NS 2.5. I'm running on Android. My current versions are:
- nativescript-angular@1.4.1-2017-01-31-1230 
- tns-core-modules@2.5.0

And the code is: 

```
...
<StackLayout tkMainContent>

    <GridLayout orientation="vertical" rows="*">

      <TabView row="0" [selectedIndex]="selectedTabIndex">
          <StackLayout *tabItem="{title: 'Title One'}"> 
             <app-content-list1></app-content-list1>
          </StackLayout>

          <StackLayout *tabItem="{title: 'Title Two'}">
             <app-content-list2></app-content-list2>
          </StackLayout>

    </GridLayout>
</StackLayout>
...
```

I've reviewed #654 and I can confirm that I am not setting fontSize and fontFamily in the TabView component.

**Comment by codeback** [comment] 2017-02-06 12:25
Sorry I forgot to add the stack trace:

```
TypeError: tabLayout.getItemCount is not a function
[1] JS:     at StylePropertyChangedHandler.TabViewStyler.setFontInternalProperty [as _applyProperty] (/data/data/com.example.app/files/app/tns_modules/ui/tab-view/tab-view.js:305:34)
[1] JS:     at StylePropertyChangedHandler.applyProperty (/data/data/com.example.app/files/app/tns_modules/ui/styling/style.js:1360:14)
[1] JS:     at Style._applyStyleProperty (/data/data/com.example.app/files/app/tns_modules/ui/styling/style.js:1117:25)
[1] JS:     at /data/data/com.example.app/files/app/tns_modules/ui/styling/style.js:1075:19
[1] JS:     at Style.DependencyObservable._eachSetPropertyValue (/data/data/com.example.app/files/app/tns_modules/ui/core/dependency-observable.js:253:18)
[1] JS:     at Style._syncNativeProperties (/data/data/com.example.app/files/app/tns_modules/ui/styling/style.js:1074:14)
[1] JS:     at TabView._onItemsPropertyChangedSetNativeValue (/data/data/com.example.app/files/app/tns_modules/ui/tab-view/tab-view.js:231:20)
[1] JS:     at PropertyMetadata.itemsProperty.metadata.onSetNativeValue [as _onSetNativeValue] (/data/data/com.example.app/files/app/tns_modules/ui/tab-view/tab-view-common.js:77:13)
[1] JS:     at TabView.ProxyObject._trySetNativeValue (/data/data/com.example.app/files/app/tns_modules/ui/core/proxy.js:83:27)
[1] JS:     at TabView.ProxyObject._onPropertyChanged (/data/data/com.example.app/files/app/tns_modules/ui/core/proxy.js:46:14)
```

**Comment by tsonevn** [comment] 2017-02-06 14:53
Hi @codeback,

I tested your case, however, was unable to reproduce this behavior, while using latest `NativeScirpt` 2.5.
To be able to investigate further your problem, could you provide sample project, which could be debugged locally. 
For your convenience I am attaching sample code:

app.component.html
```
<StackLayout tkMainContent>

    <GridLayout orientation="vertical" rows="*">

      <TabView row="0" [selectedIndex]="selectedTabIndex">
          <StackLayout *tabItem="{title: 'Title One'}"> 
             <app-content-list1></app-content-list1>
             <Label text="tab1" textWrap="true"></Label>
             
          </StackLayout>

          <StackLayout *tabItem="{title: 'Title Two'}">
             <app-content-list2></app-content-list2>
             <Label text="tab2" textWrap="true"></Label>
          </StackLayout>
        </TabView>
    </GridLayout>
</StackLayout>
```
app.component.ts
```
import { Component } from "@angular/core";

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})
export class AppComponent { 

    public selectedTabIndex=1;
}


@Component({
    selector: "app-content-list1",
    template: '<Label text="Label1" textWrap="true"></Label>',
})
export class AppContentList1 { 

    
}

@Component({
    selector: "app-content-list2",
    template: '<Label text="Label2" textWrap="true"></Label>',
})
export class AppContentList2 { 

    
}
```
app.module.ts
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { AppRoutingModule } from "./app.routing";
import { AppComponent, AppContentList1, AppContentList2 } from "./app.component";

import { ItemService } from "./item/item.service";
import { ItemsComponent } from "./item/items.component";
import { ItemDetailComponent } from "./item/item-detail.component";

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule
    ],
    declarations: [
        AppComponent,
        ItemsComponent,
        ItemDetailComponent, AppContentList1, AppContentList2
    ],
    providers: [
        ItemService
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule { }
```

**Comment by codeback** [comment] 2017-02-06 17:56
After working hours on this issue, the problem was in my style files. Specifically in this lines

```
Page {
  font-family: $primary-font;
}
````

So I think it is the same problem as in #654. So it is not a iOS-only related problem.

**Comment by NickIliev** [comment] 2017-02-07 08:06
@codeback I've tried to reproduce this issue but to no avail.
However, from first glance at the code snippet, I've noticed that you do not have **closing TabView tag** which would lead to error in Angular application. You can also try to use the official release version of nativescript-angular which of this very moment is 

Here is a sample code based on this example, that demonstrates tab-view with two tabs and a custom component with binding passed with `@Input()`

**_page.component.ts_** (can be tested by modifying [this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/15c0c45b9d068e658794e9e809193727c58fcc11/app/ui-category/tab-view/basic-tab-view/basic-tab-view.component.ts))
```

@Component({
    selector: "tab-child-component",
    moduleId: module.id,
    template: `
        <Label text="NativeScript" class="m-15 h2 text-left" color="blue"></Label>
        <ScrollView>
            <Label [text]="myData" textWrap="true" class="m-15"></Label>
        </ScrollView>
    `
})
export class NestedComponent implements OnChanges {
    @Input() data: any;
    public myData: any;

    ngOnChanges(changes: SimpleChanges) {
        this.myData = changes["data"].currentValue;
    }
}


@Component({
    moduleId: module.id,
    templateUrl: "./basic-tab-view.component.html"
})
export class BasicTabViewComponent implements OnInit {

    @ViewChild("tabview") tab: ElementRef;

    public tabindex: number;
    public content: string;
    public tabView: TabView;

    ngOnInit() {
        this.tabindex = 1;
        this.content = sampleText;
        this.tabView = this.tab.nativeElement;

        this.tabView.on("selectedIndexChanged", (args: SelectedIndexChangedEventData) => {
            console.log("old index: " + args.oldIndex);
            console.log("new index: " + args.newIndex);
        });
    }
}
```

**_page.component.html_** (can be tested by modifying[ this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/15c0c45b9d068e658794e9e809193727c58fcc11/app/ui-category/tab-view/basic-tab-view/basic-tab-view.component.html))

```
    <GridLayout orientation="vertical" rows="*">
		   <TabView #tabview row="0" [selectedIndex]="tabindex">
				<StackLayout *tabItem="{title: 'Title One'}"> 
						<tab-child-component [data]="content"></tab-child-component>
				</StackLayout>

				<StackLayout *tabItem="{title: 'Title Two'}">
						<Image class="m-t-30 m-b-15" src="res://icon" width="80" height="80"></Image>
						<Label text="NativeScript" textWrap="true" class="h2 m-x-auto" color="blue"></Label>
				</StackLayout>
		  </TabView>
    </GridLayout>
```

**Comment by tsonevn** [comment] 2017-02-07 12:39
duplicated with [#654](https://github.com/NativeScript/nativescript-angular/issues/654)

**Comment by hdeshev** [comment] 2017-02-07 14:46
#654 was a strictly iOS-related bug, which I fixed in the iOS TabView implementation.

I can't reproduce the Android crash though. @codeback, can you post a sample project? I tried it with your markup and the `Page` `font-family` setting in my `app.css`, and it works fine on my end.

**Comment by hdeshev** [comment] 2017-02-22 10:47
Closing since we can't reproduce the issue.

**Closed by hdeshev** 2017-02-22 10:47 UTC
Labels: T:Question
