### ISSUE TITLE
ListView has some extra padding-top when transitioning "back" to it on iOS

### ISSUE THREAD

**Issue by adamauckland** [NativeScript/nativescript-angular#1018] opened 2017-10-02 11:24 UTC
I've created an Angular 4/NativeScript app which is working great except ListViews all seem to gain extra padding-top when returning to them from another screen, and only in the transition. 

As soon as the "navigatedTo" event is fired, the padding-top disappears and all is well.

I've attached a tiny project demonstrating the issue, the ListView has a blue background colour which is visible only when tapping "Back". 

If this is the wrong repo to raise this in, apologies. I'll continue to try and work out where the padding is getting added.

[testlist.zip](https://github.com/NativeScript/nativescript-angular/files/1348722/testlist.zip)

**Comment by tsonevn** [comment] 2017-10-03 06:19
Hi @adamauckland,
Thank you for reporting this issue and for the attached sample project,
We reviewed your case and were able to reproduce this behavior only on iOS 11. I am attaching  GIF file was the problem is demonstrated.
For further info, please keep track on the issue.
![screencast 2017-10-03 at 9 16 41 am](https://user-images.githubusercontent.com/17448734/31112368-f4004280-a81b-11e7-8445-5817836bd2df.gif)

**Comment by NickIliev** [comment] 2017-10-04 14:49
The issue is also reproducible with a non-Angular project as posted [here](https://github.com/NativeScript/NativeScript/issues/4916) - closing this issue as duplicate and as it seems that the issue is related to the constraints in all NativeScript projects and not only in Angular.

@adamauckland  @tsonevn please track the linked issue for updates.

**Closed by NickIliev** 2017-10-04 14:49 UTC
Labels: bug, iOS

**Comment by adamauckland** [comment] 2017-10-04 20:16
Thanks everyone! Great work!
