### ISSUE TITLE
Singleton Service not working as expected on Android

### ISSUE THREAD

**Issue by jessorlisa** [NativeScript/nativescript-angular#2125] opened 2020-02-20 13:04 UTC
**Environment**
 - CLI: 6.4.0
 - Cross-platform modules: 6.4.0
 - Android Runtime: 6.4.1
 - iOS Runtime: 6.4.0
 - NativeScript-Angular: 8.20.4
 - Angular: 8.2.14
 
**Describe the bug**
According to the Angular documentation any service that declares 'root' for the value of the @Injectable() providedIn property is a singleton service. More details: https://angular.io/guide/singleton-services#providing-a-singleton-service
Sadly this is not working for Android when suspending an app and resuming it via the app icon (and not the "recent apps overview"), which I assume is a common user scenario. Each time you resume the app this way a new service instance is created. This can cause unexpected behaviour. 
The issue seems to be isolated to Android.

**To Reproduce**
- Download the following Playground project: https://play.nativescript.org/?template=play-ng&id=49IDvC
- Unzip, navigate to project folder and run `tns run android`
- Click button "Rename me!"
- Suspend app
- Resume app by clicking the app icon from the app drawer list (note: not reproducable when resumed from "recent apps overview")

**Expected behavior**
Service name is the same as before suspending the app. No new service instance is created.

**Sample project**
Playground sample project: https://play.nativescript.org/?template=play-ng&id=49IDvC
See "Steps to reproduce", issue does not occur on Playground.

**Additional context**
In very, very rare cases all is working as expected. If so please re-run the sample project. Thank you!

**Comment by edusperoni** [comment] 2020-02-20 15:39
Hi!

The way Nativescript works is it instantiates a new angular instance when you exit and enter the app (destroying the old reference). This usually doesn't happen on the web because you usually don't destroy angular without leaving the webpage (and wiping the memory with it).

The way to handle it is to implement `ngOnDestroy` on services. This method will be called when the app is suspended so you can clean up accordingly.

If you need something to run independently of angular, you should move it into a non-angular implementation and use angular services to interface with it (like you'd do with a dom or 3rd party API). Another way to do it is to use a factory provider (https://angular.io/guide/dependency-injection-providers#factory-providers), save the reference to the first Service when you instantiate it and return the same reference to other calls.

I highly recommend using `ngOnDestroy` though, as it's the "angular way" of handling app destruction. Angular handles the "frontend", which is why it's being destroyed when there's no frontend to show (all screens have been destroyed).

**Comment by saschaarthur** [comment] 2020-02-20 18:56
Hello,

Is ngOnDestroy in the end not calling Androids "onDestroy()" ? If so .. its not a good to rely on this because theres no gurantee that this is called...

**Comment by edusperoni** [comment] 2020-02-20 20:24
When android actually destroys the app, there is no javascript engine running anymore, so it's like closing a webpage. You wouldn't put code on ngOnDestroy on your webpage expecting it to run when the user closes the window. I'm not 100% sure ngOnDestroy will be called on this scenario. NS does expose the event, though: https://docs.nativescript.org/angular/core-concepts/application-lifecycle#android-activity-events

The problem is that while the app is suspended (not destroyed), you can still run JS code, which includes (among many other uses): background services, iOS delegates, notification handling, tasks, etc. The javascript engine is still running in the background, but there is no frontend running.

The idea is that everything you do in your UI should be confined to it's own instance. Every service will be a singleton **on it's own angular instance**.

**Comment by jessorlisa** [comment] 2020-02-21 08:57
Thanks for coming back to me so quickly.

I have extended the sample project by a LoggerService to make the issue more clear.

- Download the sample project
- Run `tns run android`
- The LoggerService is writing to the console every 5 seconds
- Suspend the app and resume it from the "recent apps overview"
- No constructors are called, LoggerService is still logging every 5 seconds - so everything is working just as expected
- Suspend the app again and this time resume it by clicking the app icon from the app drawer list
- All constructors are called again, a new LoggerService instance is created and now both instances are logging to the console
- No `ngOnDestroy` has been called, so there is no way for me to unsubscribe or clean anything up

Sample console output:
```
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: running instance with id: 4
JS: running instance with id: 4
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: running instance with id: 4
JS: running instance with id: 830
JS: running instance with id: 4
JS: running instance with id: 830
```

Maybe I am missing something here, but it feels like unwanted behaviour.

**Comment by edusperoni** [comment] 2020-02-21 10:42
You're not clearing your interval on ngOnDestroy, so you have a memory leak from your destroyed angular instance.

1. You open the app, angular instance 1 is created
2. Services from instance 1 created
3. App suspend, angular instance 1 destroyed
4. All ngOnDestroy called on services (clean up your subscriptions and timers!)
5. Open the app again, angular instance 2 is created
6. Services from instance 2 created
7. If you don't follow 4, you'll have memory leaks and your old instances from angular 1 will still be in memory.

You have to follow angular's lifecycle hooks.

**Comment by jessorlisa** [comment] 2020-02-21 10:49
Hmm, did you check my sample project? I am unsubscribing on ngOnDestroy in the LoggerService. The problem is, it is never called.

```
    ngOnDestroy(): void {
        console.log('calling ngOnDestroy for LoggerService!');
        this.subscription.unsubscribe();
    }
```

**Comment by edusperoni** [comment] 2020-02-21 10:53
Sorry, did not see that, I'll try it when I get to my PC shortly. Maybe the previous activity is not getting destroyed, which is weird.

**Comment by edusperoni** [comment] 2020-02-21 13:49
Indeed the activity is not being destroyed. I think this is a regression. If you open the app, go to home, open again and press back, the app will crash. I think this happens because you have 2 angular instances running at the same time but events from all activities fire on all activities (there is no isolation), so you get back button presses from activity 2 (foreground) to activity 1 (background).

This issue does not occur with @nativescript/core@6.3.1

6.4.0 (notice second activityCreated):
```
JS: Event: activityCreated, Activity: com.tns.NativeScriptActivity@eedd28e, Bundle: null
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: activityPaused, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: activityStopped, Activity: com.tns.NativeScriptActivity@eedd28e
JS: Event: saveActivityState, Activity: com.tns.NativeScriptActivity@eedd28e, Bundle: Bundle[{android:viewHierarchyState=Bundle[{android:views={1=android.view.AbsSavedState$1@1d1f671, 16908290=android.view.AbsSavedState$1@1d1f671, 2131230764=android.view.AbsSavedState$1@1d1f671, 2131230775=android.view.AbsSavedState$1@1d1f671}}], android:lastAutofillId=1073741823, android:fragments=android.app.FragmentManagerState@be28c56}]
JS: running instance with id: 422
JS: Event: activityCreated, Activity: com.tns.NativeScriptActivity@5d4b706, Bundle: null
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@5d4b706
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@5d4b706
```


6.3.1 (activity is resumed instead of created):
```
JS: Event: activityCreated, Activity: com.tns.NativeScriptActivity@610d7cf, Bundle: null
JS: calling constructor for DummyService!
JS: calling constructor for LoggerService!
JS: calling constructor for HomeComponent!
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityPaused, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityStopped, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: saveActivityState, Activity: com.tns.NativeScriptActivity@610d7cf, Bundle: Bundle[{android:viewHierarchyState=Bundle[{android:views={3=android.view.AbsSavedState$1@8bd8399, 16908290=android.view.AbsSavedState$1@8bd8399, 2131230764=android.view.AbsSavedState$1@8bd8399, 2131230775=android.view.AbsSavedState$1@8bd8399}}], android:lastAutofillId=1073741823, android:fragments=android.app.FragmentManagerState@81fd65e}]
JS: Event: activityStarted, Activity: com.tns.NativeScriptActivity@610d7cf
JS: Event: activityResumed, Activity: com.tns.NativeScriptActivity@610d7cf
```

**Comment by edusperoni** [comment] 2020-02-21 15:17
Setting on AndroidManifest.xml

```
		<activity
			android:name="com.tns.NativeScriptActivity"
                        android:launchMode="singleTask"
```

fixes the issue. This code is added for projects created using the cli (all my projects have it), but not the playground.

**Comment by jessorlisa** [comment] 2020-02-22 12:46
Downgrading @nativescript/core does not solve the issue, however setting the launchMode to "singleTask" does.

Is {N} supposed to be working with the standard launchMode? If not I think it should be part of the project templates. I checked all Hello World templates (Angular, Vue.js, TypeScript and plain JavaScript), none has set the launchMode in the AndroidManifest.xml.

Also the documentation is nowhere mentioning the launchMode flag. Is this some commonly known secret? ;)

Anyway, thanks for taking a look. I will set the launchMode to "singleTask" for now and will monitor the app's behaviour closely.

**Closed** 2020-02-23 06:17 UTC
