### ISSUE TITLE
Crash during navigation | TypeError: undefined is not an object (evaluating 'state.isPageNavigation')

### ISSUE THREAD

**Issue by jrz** [NativeScript/nativescript-angular#251] opened 2016-05-23 17:22 UTC
Was trying to build something according the groceries docs (great docs btw!)

I did a tns livesync ios --watch.

I have 2 pages with lists. I went into one, navigated back and forth.

It seems to happen when dragging (instead of pressing the back button)

```
CONSOLE LOG file:///app/pages/list/list.component.js:69:20: Itemindex = 10
CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: EXCEPTION: TypeError: undefined is not an object (evaluating 'state.isPageNavigation')
CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: STACKTRACE:
CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: back@file:///app/tns_modules/nativescript-angular/router/ns-location-strategy.js:54:26
file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:157:40
invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:281:34
onInvoke@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:45:47
invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:280:43
runGuarded@file:///app/tns_modules/zone.js/dist/zone-node.js:188:54
file:///app/tns_modules/zone.js/dist/zone-node.js:164:40
notify@file:///app/tns_modules/data/observable/observable.js:155:31
onNavigatingFrom@file:///app/tns_modules/ui/page/page-common.js:179:20
viewWillDisappear@file:///app/tns_modules/ui/page/page.js:169:34
UIApplicationMain@[native code]
start@file:///app/tns_modules/application/application.js:233:26
file:///app/tns_modules/nativescript-angular/application.js:81:26
ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:542:38
nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:80:23
anonymous@file:///app/main.js:5:36
evaluate@[native code]
moduleEvaluation@[native code]
[native code]
promiseReactionJob@[native code]
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1000f0150 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1006123f8 ffi_closure_SYSV_inner
3   0x1006141b4 .Ldo_closure
4   0x188981434 <redacted>
5   0x1889f9024 <redacted>
6   0x188b1be48 <redacted>
7   0x188a27e40 <redacted>
8   0x188a27b1c <redacted>
9   0x188a27a84 <redacted>
10  0x1889641e4 <redacted>
11  0x1862f6994 <redacted>
12  0x1862f15d0 <redacted>
13  0x1862f1490 <redacted>
14  0x1862f0ac0 <redacted>
15  0x1862f0820 <redacted>
16  0x1862e9de4 <redacted>
17  0x1837c0728 <redacted>
18  0x1837be4cc <redacted>
19  0x1837be8fc <redacted>
20  0x1836e8c50 CFRunLoopRunSpecific
21  0x184fd0088 GSEventRunModal
22  0x1889d2088 UIApplicationMain
23  0x100614044 ffi_call_SYSV
24  0x100611f70 ffi_call_int
25  0x100611adc ffi_call
26  0x1000bc630 NativeScript::FFICall::call(JSC::ExecState*)
27  0x1003bcf1c JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
28  0x1003c33a8 llint_entry
29  0x1003c33b8 llint_entry
30  0x1003c33b8 llint_entry
31  0x1003c3750 llint_entry
JavaScript stack trace:
1   __tryOrUnsub@file:///app/tns_modules/rxjs/Subscriber.js:229:22
2   next@file:///app/tns_modules/rxjs/Subscriber.js:174:34
3   _next@file:///app/tns_modules/rxjs/Subscriber.js:124:30
4   next@file:///app/tns_modules/rxjs/Subscriber.js:88:23
5   _finalNext@file:///app/tns_modules/rxjs/Subject.js:128:34
6   _next@file:///app/tns_modules/rxjs/Subject.js:120:28
7   next@file:///app/tns_modules/rxjs/Subject.js:77:19
8   emit@file:///app/tns_modules/@angular/core/src/facade/async.js:112:80
9   onHandleError@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:66:34
10  handleError@file:///app/tns_modules/zone.js/dist/zone-node.js:285:53
11  runGuarded@file:///app/tns_modules/zone.js/dist/zone-node.js:191:56
12  @file:///app/tns_modules/zone.js/dist/zone-node.js:164:40
13  notify@file:///app/tns_modules/data/observable/observable.js:155:31
14  onNavigatingFrom@file:///app/tns_modules/ui/page/page-common.js:179:20
15  viewWillDisappear@file:///app/tns_modules/ui/page/page.js:169:34
16  UIApplicationMain@[native code]
17  start@file:///app/tns_modules/application/application.js:233:26
18  @file:///app/tns_modules/nativescript-angular/application.js:81:26
19  ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:542:38
20  nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:80:23
21  anonymous@file:///app/main.js:5:36
22  evaluate@[native code]
23  moduleEvaluation@[native code]
24  @[native code]
25  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/rxjs/Subscriber.js:229:22: JS ERROR TypeError: undefined is not an object (evaluating 'state.isPageNavigation')
```

**Comment by hdeshev** [comment] 2016-06-08 07:48
Duplicate of #257

**Closed by hdeshev** 2016-06-08 07:48 UTC
