### ISSUE TITLE
Testbed broken

### ISSUE THREAD

**Issue by nakedcity** [NativeScript/nativescript-angular#584] opened 2016-12-08 17:11 UTC
When running karma and jasmine TestBed.resetTestEnvironment() throws:
```
TypeError: undefined is not an object (evaluating 'ProxyZoneSpec.assertPresent') (line 178069)
	resetFakeAsyncZone
	attemptSync
	run
	execute
	execute
	queueRunnerFactory
	execute
	fn
	attemptAsync
	run
	execute
	execute
	queueRunnerFactory
	fn
	attemptAsync
	run
	execute
	invokeTask
```

I have tried several versions of angular and zone and the problem is still happening

**Comment by hdeshev** [comment] 2016-12-09 09:08
duplicate of #479

**Closed by hdeshev** 2016-12-09 09:08 UTC
