### ISSUE TITLE
Feature: Should be able option for seperating from navigation back.

### ISSUE THREAD

**Issue by mpochron** [NativeScript/nativescript-angular#1539] opened 2018-10-04 09:23 UTC
https://github.com/NativeScript/nativescript-angular/blob/6e45af023a4196597d829e2ccd41b6c29fb72b0f/nativescript-angular/directives/dialogs.ts#L132

As topic.

**Comment by tsonevn** [comment] 2018-10-04 11:38
Duplicate of #1503

**Closed by tsonevn** 2018-10-04 11:38 UTC
