### ISSUE TITLE
Is there a NativeScript Angular rich text editor?

### ISSUE THREAD

**Issue by yuzhang666** [NativeScript/nativescript-angular#996] opened 2017-09-18 17:32 UTC
NativeScript has a lot native components, however, there is no rich text editor.
We are looking for a text editor component that supports at least: range selection, bold, italic, underline, bullets, numbers, alignment and imbedded images.
We are also looking for NativeScript plugins that integrates ZSSRichTextEditor or CKEditor.
But we got no luck.

Just want to ask the community if anyone has the same requirements and looks for help?
Is there anyone making a NativeScript Angular text editor or a plugin?

**Comment by NickIliev** [comment] 2017-09-25 11:49
@yuzhang666 there is no out-of-the-box feature or plugin providing this functionality.
This functionality is already logged as a feature [here](https://github.com/telerik/nativescript-ui-feedback/issues/297).

Closing as duplicate of  [https://github.com/telerik/nativescript-ui-feedback/issues/297](https://github.com/telerik/nativescript-ui-feedback/issues/297)

**Closed by NickIliev** 2017-09-25 11:49 UTC

**Comment by MadyZaid** [comment] 2023-08-30 20:56
I have created this one, It is not a plugin but a rich text editor that is based on Webview and nativescript-webview-interface

https://github.com/MadyZaid/nativescript-webview-rich-text-editor
