### ISSUE TITLE
Router Outlet not working inside RadSideDrawer

### ISSUE THREAD

**Issue by ahmedelgendy** [NativeScript/nativescript-angular#366] opened 2016-07-24 17:40 UTC
I want to use <router-outlet> Like that:
 <RadSideDrawer> <template drawerMain> <router-outlet></router-outlet></template></RadSideDrawer> 

but i get the error Cannot find primary outlet to load Component

The component has

 directives: [NS_ROUTER_DIRECTIVES, ROUTER_DIRECTIVES]
The HTML has <router-outlet> Tag so it should work

Code: https://github.com/telerik/nativescript-ui-samples-angular/issues/13

Notice: when i remove RadSideDrawer codes from HTML file works normally. 

Any solutions? Thanks

**Comment by matt4446** [comment] 2016-07-25 10:34
First brought up here: https://github.com/NativeScript/nativescript-angular/issues/343
Both the `page-router-outlet` & `router-outlet` have issues at the moment. Then again it is still early days.

**Comment by vakrilov** [comment] 2016-08-01 15:17
Duplicate of #343

**Closed by vakrilov** 2016-08-01 15:17 UTC

**Comment by chenyingyin** [comment] 2016-12-01 05:26
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
