### ISSUE TITLE
Changelog does not mention 8.20.2 & 8.20.3

### ISSUE THREAD

**Issue by dmytro-gokun** [NativeScript/nativescript-angular#2074] opened 2019-11-15 16:11 UTC
Were there any changes in those releases?

**Comment by Pandishpan** [comment] 2019-11-18 11:50
@dmytro-gokun 

I think there are quick fixes for some regressions, the last major update created some BUGs and especially some breaking changes due to the scoped NPM packages :(


You can take a look at what was changed from the pull requests:

https://github.com/NativeScript/nativescript-angular/pull/2064
https://github.com/NativeScript/nativescript-angular/pull/2071

**Comment by tbozhikov** [comment] 2019-11-18 15:37
Hi @dmytro-gokun. Indeed, the CHANGELOG in `master` branch does not contain info on these versions. They are described in the [CHANGELOG file in the release branch](https://github.com/NativeScript/nativescript-angular/blob/release/CHANGELOG.md). When `release` is merged into `master`, they will be visible there.

**Closed by tbozhikov** 2019-11-18 15:37 UTC

**Comment by dmytro-gokun** [comment] 2019-11-18 17:20
@tbozhikov With all respect, i do not think this is a good answer. As a library user, i want changelog/release notes be visible and not hidden in some branch. Thank you.

**Comment by tbozhikov** [comment] 2019-11-19 15:38
@dmytro-gokun `release` is now merged into `master`, so the `CHANGELOG` there is updated.
