### ISSUE TITLE
where RouterExtensions?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#381] opened 2016-08-01 06:23 UTC
_From @peirancao on July 30, 2016 5:12_

https://docs.nativescript.org/angular/core-concepts/navigation-angular.html#navigation-options

_Copied from original issue: NativeScript/NativeScript#2534_

**Comment by NickIliev** [comment] 2016-08-01 06:23
_From @tsonevn on August 1, 2016 6:22_

Hi @peirancao, 

Could you provide some more info about your problem. It would also help if you could give me some sample project. 

Regards,
@tsonevn

**Comment by vakrilov** [comment] 2016-08-01 14:54
Duplicate of #380

**Closed by vakrilov** 2016-08-01 14:54 UTC

**Comment by diegomelo182** [comment] 2016-11-22 18:31
I'm found "RouterExtensions" on "nativescript-angular/router", look this code:

``` typescript
import {RouterExtensions} from "nativescript-angular/router";

export class YourComponent {
	public constructor (private routerExtensions: RouterExtensions) {
		this.page.actionBarHidden = true;
	}
}
```

**Comment by weijyewang** [comment] 2018-03-23 02:28
Thanks @diegomelo182   from saving my time digging into NativeScript code to search for the modules. The documentation could improve to specify where to import `RouterExtensions`
