### ISSUE TITLE
Warnings in default angular codesharing build

### ISSUE THREAD

**Issue by aescarcha** [NativeScript/nativescript-angular#1642] opened 2018-12-01 19:23 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.1
 - NativeScript-Angular: 7
 - Angular: 7
 
**Describe the bug**
On a clean code sharing install, I get a lot of warnings in the console when running the application, I don't get them in the **pet-bros-lite** sample project

**To Reproduce**
ng new --collection=@nativescript/schematics --name=my-app --shared
cd my-app
tns run android --bundle

**Expected behavior**
No warnings should be thrown (is everything ok?)

**Additional context**
This is the output:
```
Successfully synced application org.nativescript.myapp on device emulator-5554.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
12-01 20:18:27.964  9411  9411 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
```

**Comment by tsonevn** [comment] 2018-12-03 07:48
Duplicate of https://github.com/NativeScript/android-runtime/issues/1210

**Closed by tsonevn** 2018-12-03 07:48 UTC

**Comment by aescarcha** [comment] 2018-12-03 18:32
> Add to your `App_Resources/Android/app.gradle` below `android {...}`:
> 
> ```
> 
> configurations.all {
>   resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>     def requested = details.requested
>     if (requested.group == "com.android.support") {
>       if (!requested.name.startsWith("multidex")) {
>         details.useVersion "26.+"
>       }
>     }
>   }
> }
> ```

thank you very much, couldn't find the other issue.
