### ISSUE TITLE
Reference to a non-exported function in 'SocketIOModule'

### ISSUE THREAD

**Issue by Dhruvi109** [NativeScript/nativescript-angular#1664] opened 2018-12-17 10:08 UTC
Error: Failed to compile.
```
ERROR in Error during template compile of 'AppModule'
Reference to a non-exported function in 'SocketIOModule'
'SocketIOModule' contains the error at nativescript-socketio/angular/index.ts(25,10).
```
below are the details of package json
```
"tns-android": {
"version": "5.0.0"
},
"tns-ios": {
"version": "5.1.0"
}

"@angular/compiler-cli": "~7.1.0",
"@ngtools/webpack": "~7.1.0",
```
we are facing above issue only in IOS when we execute following command
```
tns build ios --bundle --env.aot --env.uglify;
```
Has anyone ever had this problem? Need help.

**Comment by NickIliev** [comment] 2018-12-17 10:52
@Dhruvi109 the issue seems related to a plugin you are using (`nativescript-socketio`) - can you provide a sample project that can reproduce the issue so we could investigate this one?

**Comment by tsonevn** [comment] 2018-12-17 11:12
Duplicate of https://github.com/NativeScript/NativeScript/issues/6716

**Closed by tsonevn** 2018-12-17 11:12 UTC
Labels: needs more info
