### ISSUE TITLE
[SegmentedBar] Segmented Bar Views not showing when switching in NS 4.0

### ISSUE THREAD

**Issue by relez** [NativeScript/nativescript-angular#1286] opened 2018-04-16 19:39 UTC
Hi guys, thanks for your hard work on making NS an awesome tool for develop mobile apps. I am working on a project which I started with NS 3.4, since I updated to NS 4.0 I am having this issue in my dashboard page, I am using a TabView to choose between Dashboards and a SegmentedBar in each of them to switch some information inside the dashboard. Since I updated to NS 4.0 none of the tabs are working except the first of each SegmentedBar. Here is a sample app in GitHub which you can see what I am doing and whats going on.

[https://github.com/relez/tns-segmentedbars.git](https://github.com/relez/tns-segmentedbars.git)

Thanks for your help!

**Comment by NickIliev** [comment] 2018-04-18 06:12
@relez thank you for reporting this issue and providing a test project. I can confirm that indeed this is unexpected behaviour and marking this one as a bug. We will post any related information, workarounds and fixes in this issue.

The issue might be related to binding not being respected when changed from inside the `selectedIndexChange` event callback. Works as expected in NativeScript Core - the same code base does not work in Angular.

Steps to reproduce:
- use[ this test application](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/sedmentedBarNG)
- [trying to change the `visibility` via a boolean property on `selectedIindexChange`](https://github.com/NickIliev/NS-Issues-2018/blob/master/NativeScript/sedmentedBarNG/app/item/items.component.ts#L26-L32) - **not working**
- the same code works [when triggered from button tap.](https://github.com/NickIliev/NS-Issues-2018/blob/master/NativeScript/sedmentedBarNG/app/item/items.component.ts#L50-L54)
- the [same code works in NativeScript Core](https://github.com/NickIliev/NS-Issues-2018/blob/master/NativeScript/segementedBarBinding/app/main-page.ts#L21-L36).

As a side note, the arguments received via [`SelectedIndexChangedEventData `interface are always `undefined`](https://github.com/NickIliev/NS-Issues-2018/blob/master/NativeScript/sedmentedBarNG/app/item/items.component.ts#L28-L30)

**Comment by gummibjorn** [comment] 2018-04-20 14:35
if you bind (selectedIndexChanged) and (loaded) on the segmentedBar it seems to work. weird

```
<SegmentedBar [items]="items" (selectedIndexChanged)="indexChanged($event)" (loaded)="onBarLoaded($event)"></SegmentedBar>
```

where indexChanged() actually toggles the boolean but onBarLoaded() is just an empty function

**Comment by razorsyntax** [comment] 2018-04-22 16:06
I can confirm this as well and when I debug iOS I get the following error:

> CONSOLE ERROR [native code]: ERROR TypeError: _co.onTabSwitch is not a function. (In '_co.onTabSwitch($event)', '_co.onTabSwitch' is undefined)

**Comment by relez** [comment] 2018-04-30 20:51
Hi there, any news on this issue?

Thanks!

**Comment by vakrilov** [comment] 2018-05-02 10:43
The issue was caused by a bug in the `tns-core-modules` package addressed in https://github.com/NativeScript/NativeScript/pull/5724. 
You can switch to `tns-core-modules@next` to try it out.

**Closed by vakrilov** 2018-05-02 10:43 UTC
Labels: bug
