### ISSUE TITLE
ListView mixing component data in angular

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1245] opened 2018-03-20 08:34 UTC
_From @waszqba on March 20, 2018 8:30_

## Please, provide the details below:
When I put a component as a list item, the listView mixes data, when I change a piece of data influencing appearance of the component instance, the change is visible on further instances taking place of the one that has actually changed it's data.

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
yes

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.1 for both
- Angular: 5.2.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
home.component.html:
```
<ListView [items]="items" (itemTap)="onItemTap($event)">
    <ng-template let-item="item" let-i="index" let-odd="odd" let-even="even">
        <my-component [item]="item"></my-component>
    </ng-template>
</ListView>
```
the .ts file makes an API request onInit, ant that's all there's to it

`my-component` is in a separate module if it helps. The module imports NativescriptCommonModule and NativeScriptModule and declares its components, nothing more.

`my-component.conponent.ts` contains `moduleId: module.id` in its declaration has one input for the item and 3 public variables, one of which is boolean declared to `true` and it's broken by ListView, as if I set it to false on first few instances, it remains false on any further loaded instance.

`my-component.component.html` contains two sub-component calls with some data passed to it. Those sub-components have their own independent data and this data also gets copied from previous instance of my-component that had taken this place.

_Copied from original issue: NativeScript/NativeScript#5567_

**Comment by tsonevn** [comment] 2018-03-20 08:53
HI @waszqba, 
Can you provide sample project, which could be used for debugging and demonstrates the issue?

**Comment by waszqba** [comment] 2018-03-20 09:41
Hi @tsonevn, here it is:
https://play.nativescript.org/?template=play-ng&id=al5egs&v=18

**Comment by tsonevn** [comment] 2018-03-21 09:07
Hi @waszqba,
Thank you for the sample project.
I reviewed it and was able to recreate the issue. 
As a workaround, I would suggest defining the ui directly in the ListView's template, instead of using a custom component, and set up boolean property in the array for every item. I am attaching [sample ](https://play.nativescript.org/?template=play-ng&id=al5egs&v=19) project, where the workaround is demonstrated.

**Comment by waszqba** [comment] 2018-03-21 10:03
Thank you for your time, unfortunately, my ui consists of nested components and the issue would persist. Also, the component itself is a bit too complex to be defined in my home component and the data is dynamic so no luck there too :(
However I keep my fingers crossed the fix would be easy to do. I'd be glad if you'd respond to this topic if you'll manage to resolve this issue.

**Comment by tsonevn** [comment] 2018-03-22 12:28
Hi @waszqba,
Thank you for writing us back.
This problem is still under review, At this time I would suggest keeping track on the issue, and we will provide more info on it when we find what is causing this strange behaviour.

**Comment by waszqba** [comment] 2018-05-10 08:08
Hi, how are you guys doing? Is there a chance you'll find the solution? Or is it a bigger issue?

**Comment by shabib3** [comment] 2018-05-30 15:58
@tsonevn - any update here?

**Comment by vakrilov** [comment] 2018-05-31 09:03
Hey @waszqba a more detailed view of the application.

Some more info on how the list-view works. It uses view recycling - whenever an item scrolls out of the view port, the component that was rendering it is not destroyed. It is put in a pool of recycled views and reused when an new item scrolls into view ([more info in this blog](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f)).

When you put some state (in your case the `bool: boolean` field) inside the component - this state is not cleared when the same component is reused to show another item in your collection. 
You have two options:

1. (Not so great options) You can implement [`OnChanges`](https://angular.io/api/core/OnChanges) and clear the state in the component when the `item` is changes. This means the state will be cleared when the component is reused. NOTE: The result is that the sate of your component is lost when it scrolls out of view. It might be the behavior that you want, but usually it is not.
2. (Better option) Keep your state in the model(the items). This is similar to the example @tsonevn showed. This way the items will be shoed the same way even is shoed inside reused component.

I hope that clarifies things a bit.

**Comment by waszqba** [comment] 2018-06-04 05:30
Hi, @vakrilov, unfortunately I'm unable to store the data @tsonevn sugested, so the only thing I can do is the OnInit hook :/
I'm currently displaying a scrollview with stacklayoutin the component, which is über sluggish solution, so I guess I'll have to hook the oninit... I really hope there wil be a solution to this problem so the listview will be more universal to use.

**Comment by shabib3** [comment] 2018-06-04 19:13
We are facing difficult problems with this issue, and even couldn't find a workaround for this, and users are facing and getting the wrong data/state that make users misbehave. 
Please advice us with any ETA's, and workarounds/fix if exists.

Btw, I am not sure it duplicates the issue I opened -> https://github.com/NativeScript/NativeScript/issues/5621

Thanks a lot guys :)

**Comment by shabib3** [comment] 2018-06-27 22:14
@vakrilov - Just succeed of implementing the second solution that you suggested. Works great!!!

**Comment by vakrilov** [comment] 2018-07-27 06:23
@shabib3 - Great to hear that!

**Comment by waszqba** [comment] 2018-07-27 11:50
@vakrilov I've tried the suggested workaround and unfortunately more problems spawned than got fixed :/ also, I don't think that this workaround makes problem disappear, so I would reopen this issue

**Comment by RoyiNamir** [comment] 2018-07-28 07:56
@tsonevn , @NickIliev  Hey:)
Sorry to interfere  , but this bug has other consequences too.
I'm talking about people who migrate to Nativescript ( as a test to see how's it's going)  : 

I;m not talking about a master detail app , but a real company app.
they will probably will reach to a situation where they need components scrolling inside a listview.

If they find out that such a simple task - which is not very much to ask - has problems with  recycing   , they will think twice about the decision if- ever - to move to NS. This can be a deal breaker.

It's not like other solution like setTimeout for re-change-detect angular - which is tollerated.

Almost everyone wants to have scroll list of components ( chats , instagram , images etc).

You can;t force them to put the UI in the template itself. You just cant.

I;m saying it becuase I care and I think it should be fixed asap. 

(full disclousre - I dont have that problem in my app yet  , but I see others have).

**Comment by shabib3** [comment] 2018-07-28 09:05
I agree with @RoyiNamir!
I talked with @vakrilov in the past for suggested solution for this issue.
I suggested a mechanism that wrap the item payload with the properties of yhe component so the recycling will work with all the data and not just the passed payload and would recycle the rest of the UI properties.

**Comment by grendizeras** [comment] 2018-07-29 19:53
Have the same bug... don't know what to do... Cursing the day I switched to NS!

**Comment by shabib3** [comment] 2018-07-29 20:16
@grendizeras - I feel you... it took me some time to understand how to solve this...
The thing is to pass the UI binding information also as `Input` from the page is in-charge of the ListView, because the listView recycling process isn't recalculate the properties that found in the used Component, it has to come from the component that contains that ListView.

if you need more help talk to me in Slack

**Comment by vakrilov** [comment] 2018-07-30 15:54
Thanks for the further feedback. 
I have reopened this one so that we can have further discussion.

@RoyiNamir I totally get you points about migrating to NS from web. I don't think that this is a matter of forcing you to put your UI in the template - you can still use components. It is matter where you keep the view-state of the items. 
In many cases you won't even have view-state for example - standard master-detail with "tap to navigate". In other you will - for example multiple selection or list-view with inputs. The second cases - you will need to take care of that state.

I can see how this causes confusion if you are coming from web. One important difference is that:
- In **web** using `*ngFor` for **1000 items** collection - you will have **1000 instances** of components rendered.
- in  **NS** using `ListView` for  **1000 items** collection - you will have **~10 instances**(or however you can fit on the screen at once) of components rendered.

>Note: Browsers will probably handle 1000 items (it might be lag-ish though). In mobile app rendering that many UI views will cause memory and performance issues. That is because dom-elements are generally lighter than mobile UI Views.

You can still use `*ngFor` in NativeScript if you have smaller number of items. For bigger collection `ListView` is the better choice because of virtualization and recycling. That leads us to the problem:  you cannot fit the state of 1000 items in 10 components unless you do some extra work.

One approach (which I suggested before) is to add the view-state information ("checked", "selected", "highlighted", etc.) in the items or wrap you model objects with view-model objects(which contain their view-state) and use those in the `ListView`.

Lets explore other options or things we can do in `nativescript-angular` or perhaps as a plug-in to make things easier

**Comment by RoyiNamir** [comment] 2018-07-31 17:52
Hi @vakrilov 
Thanks for response.

I might be missing something , but let's talk about the basic situation where a user fetch an array of data (say 100 , so no  `ngFor`) and wants to scroll it in a listview : 

```
<ListView [items]="items"  >
    <ng-template let-item="item" let-i="index" let-odd="odd" let-even="even">
        <my-component [item]="item"></my-component>
    </ng-template>
</ListView>
``` 

Are we agreeing in the fact that ` [items]="items" ` must be present ?
 So how would you bind each ngTemplate without ` <my-component [item]="item"></my-component>` ?

Is there any other way ?

(assuming that component is very complexed , and we dont unwrap the html into the ngTemplate

**Comment by godfrednanaowusu** [comment] 2018-08-03 11:09
i am really disappointed that something as basic as adding a listview with data has this issue, i have been searching for a solution for a very long time and i seem not to be getting anywhere, 

My problem is that i add data to listview but after scrolling the selection changes. 

exactly like this https://appetize.io/app/qjq797e7zhk0f4hhu0k20btucc?device=nexus5&scale=75&orientation=portrait&osVersion=7.1

EXACTLY LIKE THIS. Please i need help, my project deadline is past 1month. Please.

i use core xml and typescript, no angular

**Comment by NickIliev** [comment] 2018-08-03 13:20
@godfrednanaowusu  the appetize demo is now good for demonstration as it lacks the codebase used - use playground to demonstrate what you want to achieve. 

Note that the above discussion is actually not a bug but a conceptual difference between using a big list of items in web and in the context of mobile development. As noticed [here ](https://github.com/NativeScript/nativescript-angular/issues/1245#issuecomment-374872300)the solution would be to provide a variable (boolean, number or else depending on your logic) in your model and reuse its value to handle the state of the current list view item cell (demo playground [here](https://play.nativescript.org/?template=play-ng&id=al5egs&v=21)).

**Comment by vakrilov** [comment] 2018-08-28 16:54
Hey folks.
Just wrote a blog post on the topic - [Managing Component State in NativeScript ListView](https://medium.com/@alexander.vakrilov/managing-component-state-in-nativescript-listview-b139e45d899b). It explains the problem in detail and proposes some actual solutions (and some code in [this repo](https://github.com/vakrilov/fun-with-state-lists)). 

I hope you can use it as a start-point in forming even better solutions in your projects.

**Comment by xlmnxp** [comment] 2018-09-28 07:37
@vakrilov it's work :+1:

**Comment by waszqba** [comment] 2018-11-21 07:50
Guys, I see the discussion went in the direction of conceptual debate, but the thing is, while listView is great for static elements, it should absolutely support component states without having to rework the logic in order to move states to the parent element. Can we try to focus on that? If there's anything I can do to make this work any easier, let me know, I'll be glad to help, or at least try to do so.

**Comment by vakrilov** [comment] 2018-11-28 21:10
The thing is - the `ListView` cannot do automatic "cleanup" of your component state when recycling.

Actually, with the `Attach View-State to Item` approach form the blog, you can still make changes to the state and it will be carried around with the item. So when the components are recycled they will also get the right view-state for the item they are rendering. This means that you can make changes to the view-sate inside methods of the component.

**Closed** 2019-01-08 14:49 UTC
Labels: list-view
