### ISSUE TITLE
Is there a way to capture key events like the clear event from keyboard on especially for empty text fields? 

### ISSUE THREAD

**Issue by shubhambitqit** [NativeScript/nativescript-angular#1906] opened 2019-07-15 12:54 UTC
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsonevn** [comment] 2019-07-16 05:04
Duplicate of https://github.com/NativeScript/NativeScript/issues/7349

**Closed by tsonevn** 2019-07-16 05:04 UTC
