### ISSUE TITLE
Button tap inside ActionBar not working

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1319] opened 2018-05-08 13:32 UTC
```
<ActionItem  (tap)="goToNext()">
	<Button backgroundColor="green" class="last" text="1"></Button>
</ActionItem>
<ActionItem>
	<Button (tap)="goToNext()" class="last" backgroundColor="red" text="2"></Button>
</ActionItem>
<ActionItem (tap)="goToNext()">
	<Label class="last" text="3" padding="10" backgroundColor="green"></Label>
</ActionItem>
<ActionItem>
	<Label (tap)="goToNext()" class="last" padding="10" text="4" backgroundColor="green"></Label>
</ActionItem>
```
while running above code `tap` event on button with `text="2"` not working. everything else runs and works as expected.

here is playground demo to check the error.
[https://play.nativescript.org/?template=play-ng&id=r2C7nK&v=2](https://play.nativescript.org/?template=play-ng&id=r2C7nK&v=2)

**Comment by NickIliev** [comment] 2018-05-10 15:34
@bhavincb I can confirm that this is a known issue and currently we are recommending using the `tap` event on the `ActionItem` until the issue is resolved.

Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/3578](https://github.com/NativeScript/NativeScript/issues/3578)

**Closed by NickIliev** 2018-05-10 15:34 UTC
