### ISSUE TITLE
Using *ngIf in FormattedString renders wrong order

### ISSUE THREAD

**Issue by Burgov** [NativeScript/nativescript-angular#1313] opened 2018-05-07 08:17 UTC
See: https://play.nativescript.org/?template=play-ng&id=2mT3se

The span containing the text "first" should be displayed before the other, but it is displayed after. Remove the *ngIf, and it works as expected.

**Comment by tsonevn** [comment] 2018-05-07 09:32
Duplicate of [#1119](https://github.com/NativeScript/nativescript-angular/issues/1119)

**Closed by tsonevn** 2018-05-07 09:32 UTC
