### ISSUE TITLE
Feature Request: Ahead of Time Compilation

### ISSUE THREAD

**Issue by colinskow** [NativeScript/nativescript-angular#484] opened 2016-10-02 21:50 UTC
I've noticed that the Angular bootstrap process takes several seconds on one of my apps and think NativeScript/Angular apps could start up much faster with [Angular 2's AOT compilation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html).

**Comment by vakrilov** [comment] 2016-10-04 07:52
Closing - Duplicate of #386

**Closed by vakrilov** 2016-10-04 07:52 UTC
Labels: T:Feature
