### ISSUE TITLE
Styling bug after navigation (padding + border element) 

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#110] opened 2016-03-14 02:15 UTC
@vakrilov 

So it seems to only apply to the `<Border>` element, which I believe is/has become obsolete now (I'll be removing the border element anyway) so it is not so much of a big deal. 

As previously mentioned in the routing and navigation issue https://github.com/NativeScript/nativescript-angular/issues/18 ...

But more specifically the issue appears to be with the border element (and *only* as part of an additional component from the page component). When the page loads the padding from a CSS file it is not applied, but after navigation the padding is applied (see the two images below):  

Ignore the action bar - I started adding my own. 

![before-nav_20160314015641](https://cloud.githubusercontent.com/assets/1550939/13733234/0ca7b574-e988-11e5-9978-574853d88bd3.png)
![after-nav](https://cloud.githubusercontent.com/assets/1550939/13733235/0f499bda-e988-11e5-8d77-f81390ee9f9b.png)

I've added the same view component for both the [start](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/layout-bug/app/pages/startPage/startPage.ts) & [test](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/layout-bug/app/pages/testPage.ts) page so the collection of elements should be identical. After navigation, one would expect equal states of the components. The [padding ](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/layout-bug/app/app.less#L99-L102)

I've branched my project [here](https://github.com/matt4446/WhatsMyScore2-NativeScript/tree/layout-bug)

The inconsistent [component](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/layout-bug/app/controls/list/list.ts#L13-l25)
Changing Border -> StackPanel loads the padding correctly. 

I expected part of the [template](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/layout-bug/app/pages/startPage/startPage.html#L67-l75) to act in the same way as the component above, but it didn't, which leads to a conclusion that it only does this when it is  part of a component. 

This effect (not loading the CSS) isn't appearing anywhere else in my pages / components I don't think.

**Comment by vakrilov** [comment] 2016-03-18 12:58
Thanks for the sample and the explanations.
Indeed, I managed to reproduce it. However, as you said, only with the `Border` element. It is possible that this is a bug in the `Border` element layout logic, but since it is obsoleted it is not worth investigating it further.
I'm closing the issue for now - if it reappears again with other element we will reopen and investigate.

**Closed by vakrilov** 2016-03-18 12:58 UTC
