### ISSUE TITLE
TextView's new line is not working on android device version 4.4.2/API 19 – 20

### ISSUE THREAD

**Issue by kumarandena** [NativeScript/nativescript-angular#1273] opened 2018-04-10 14:27 UTC
Hi Team,

I have to support min android version of 4.4.2 for my app but faced small issue as mentioned. 

TextView's new line(device option) is not working on android device as expected.

**Device details -** 
Android Version : 4.4.2
API : 19 – 20
Device Name : SM-T231

.Thanks

**Comment by tsonevn** [comment] 2018-04-11 07:03
Hi @kumarandena,
This problem seems to be fixed in the latest NativeScript 4.0.0. Try to upgrade to the latest version.
```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.test12732",
		"tns-android": {
			"version": "4.0.0"
		}
	},
	"dependencies": {
		"@angular/animations": "~5.2.0",
		"@angular/common": "~5.2.0",
		"@angular/compiler": "~5.2.0",
		"@angular/core": "~5.2.0",
		"@angular/forms": "~5.2.0",
		"@angular/http": "~5.2.0",
		"@angular/platform-browser": "~5.2.0",
		"@angular/platform-browser-dynamic": "~5.2.0",
		"@angular/router": "~5.2.0",
		"nativescript-angular": "~5.3.0",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.5.2",
		"tns-core-modules": "~4.0.0",
		"zone.js": "~0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.7.0",
		"typescript": "~2.7.2"
	}
}

```

**Closed by tsonevn** 2018-04-11 07:03 UTC

**Comment by dpdragnev** [comment] 2018-04-17 19:57
@tsonevn What is the alternative if you cannot upgrade your project to 4.0.0?

**Comment by tsonevn** [comment] 2018-04-18 05:17
Hi @dpdragnev,
Unfortunately, we do not have a workaround that can be used with the old modules(3.4.1). The fix for this issue was related to some major changes which are available only in 4.0.

**Comment by dpdragnev** [comment] 2018-04-18 13:51
Thank you @tsonevn.  The problem is that the app in QA now and I cannot make changes of this magnitude.  Is there other component you can suggest to use instead of TextView?  I need it for the message part of our Contact Us screen.

**Comment by vforv** [comment] 2020-05-22 13:33
The issue still exists with 6.5.0 version.
