### ISSUE TITLE
ViewHolder views must not be attached when created?

### ISSUE THREAD

**Issue by kshipraShelke** [NativeScript/nativescript-angular#1392] opened 2018-06-21 07:40 UTC
```
System.err: java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6687)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
System.err:     at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
System.err:     at android.support.v7.widget.GapWorker.prefetchInnerRecyclerViewWithDeadline(GapWorker.java:332)
System.err:     at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:348)
System.err:     at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
System.err:     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
System.err:     at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)

```
Arising this error on RadListView Scroll
but working properly in another components, only happening in the main component Like Dashboard

I dont understand the root cause of error
Can somebody help regarding this??

**Comment by NickIliev** [comment] 2018-06-21 11:50
@kshipraShelke can you please provide a sample project tor Playground demo illustrating the issue along with the involved codebase.

**Comment by kshipraShelke** [comment] 2018-06-22 04:44
Unable to provide sample .
RadlistView working properly in the demo

Also, working in other components

**Comment by NickIliev** [comment] 2018-07-17 10:42
@kshipraShelke test with the latest `nativescript-ui-listview` and the latest `tns-core-modules` and let me know if you are still experiencing the issue. 

Closing the issue as I am unable to reproduce this one but I will reopen the issue if you can provide a sample project or steps to reproduce it.

**Closed by NickIliev** 2018-07-17 10:42 UTC
Labels: needs more info
