### ISSUE TITLE
Unable to build using --env.aot in shared app.

### ISSUE THREAD

**Issue by gonick** [NativeScript/nativescript-angular#1678] opened 2018-12-28 19:19 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.0 version and is up to date.
✔ Component tns-core-modules has 5.1.1 version and is up to date.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.0 version and is up to date.
 
**Describe the bug**

if I build the app without --env.aot I get no error. But, while building with --env.aot I get error as:

ERROR in : Type AppComponent in /src/app/app.component.tns.ts is part of the declarations of 2 modules: AppModule in /src/app/app.module.ts and AppModule in /src/app/app.module.tns.ts! Please consider moving AppComponent in /src/app/app.component.tns.ts to a higher module that imports AppModule in /src/app/app.module.ts and AppModule in /src/app/app.module.tns.ts. You can also create a new NgModule that exports and includes AppComponent in /src/app/app.component.tns.ts then import that NgModule in AppModule in src/app/app.module.ts and AppModule in /src/app/app.module.tns.ts.

**Comment by tsonevn** [comment] 2018-12-31 07:49
Duplicate of https://github.com/NativeScript/nativescript-schematics/issues/140

**Closed by tsonevn** 2018-12-31 07:49 UTC
