### ISSUE TITLE
StackLayout Height  Property not working in ListView

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1213] opened 2018-03-01 17:33 UTC
when using StackLayout inside ng-teplate within list view, StackLayout height property not working.
i'm attching nativescript playground project link .
[https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=9](https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=9)

```
<ListView [items]="a"  class="list-group">
	<ng-template let-country="item" let-i="index" let-odd="odd" let-even="even">
		<StackLayout width="250"  height="250" orientation="horizontal" backgroundColor="palegreen">
			<Label  text="Label 2"  backgroundColor="green"></Label>
		</StackLayout>
	</ng-template>
</ListView>
```

here expected output should be in listview many stacklayout with width 250 and height 250. 
but all the stacklayout has correct width but height not working.
Note: tried almost every unit for height value like "px","%" etc but still not working

**Comment by bhavincb** [comment] 2018-03-01 17:54
if using Work around like minHeight,
if stacklayout has set minHeight and inside it there is GridLayout than GridLayout's height property not working properly while using percentage value.

`<ListView [items]="a"  class="list-group">
	<ng-template let-country="item" let-i="index" let-odd="odd" let-even="even">
		<StackLayout width="250" minHeight="400" orientation="horizontal" backgroundColor="palegreen">
			<GridLayout rows="*,*" columns="auto" width="50%" height="50%"  backgroundColor="lightgray">
				<Label row="0" text="Label 1" col="0" backgroundColor="red"></Label>
				<Label row="1" text="Label  2" col="0" backgroundColor="green"></Label>
			</GridLayout>
		</StackLayout>
	</ng-template>
</ListView>`
here Label 1 and Label 2 both should have 125 height but instead it has height auto.
below is nativescript playhround project link
[https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=10](url)

**Comment by tsonevn** [comment] 2018-03-02 09:44
Duplicate of [#5441](https://github.com/NativeScript/NativeScript/issues/5441).
At this time it seems that there is a general issue with Layout measurement inside the ListView template. For further info, I would suggest keeping track of the issue mentioned above.

Meanwhile, I can suggest specifying the height of the GridLayout in the template as follow.
```
<ActionBar title="Home" class="action-bar">
</ActionBar>

<ListView [items]="a"  class="list-group">
	<ng-template let-country="item" let-i="index" let-odd="odd" let-even="even">
		<StackLayout width="250" minHeight="400" height="400" orientation="horizontal" backgroundColor="palegreen">
				<GridLayout rows="*,*" columns="auto" width="50%" height="200" verticalAlignment="top"  backgroundColor="lightgray">
					<Label row="0" text="Label 1" col="0" backgroundColor="red"></Label>
					<Label row="1" text="Label  2" col="0" backgroundColor="green"></Label>
				</GridLayout>
		</StackLayout>
	</ng-template>
</ListView>
```

**Closed by tsonevn** 2018-03-02 09:44 UTC

**Comment by bhavincb** [comment] 2018-03-02 18:41
general issue you mentioned with Layout measurement inside the ListView template, is only for ios. i had this issue in android. if it is same issue then please change it's title.

**Comment by ehigiepaul** [comment] 2018-07-06 06:33
Yes i have the same issue and i feel very stupid to thing i was the one doing it wrong .
please before i jump to conclusion can you look at my code.

```
 <StackLayout class="p-x-20 p-b-20" height="auto">
                        <Label text="Comments" textWrap="true" class="h1 bold m-t-10" color='black' />
                        <ListView items="{{ comments }}" height="200%" >
                            <ListView.itemTemplate>
                                <StackLayout >
                                    <!-- comments area      -->
                                    <GridLayout rows="*" columns="40,10,*" height="100%">
                                        <GridLayout col="0" row="0">
                                            <Image src="{{image}}" stretch="aspectFit" row="0" col="0" />
                                        </GridLayout>
                                        <StackLayout row="0" col="2" height="100%">
                                            <Label text="{{user}}" textWrap="true" class="bold" color='black' />
                                            <HtmlView html="{{comment }}" />
                                            <Label text="{{date}}" textWrap="true" />
                                        </StackLayout>
                                    </GridLayout>
                                    <!-- comments end -->
                                </StackLayout>
                            </ListView.itemTemplate>
                        </ListView>
                    </StackLayout>
```

**Comment by SephReed** [comment] 2019-05-14 20:19
I'm also having issues with grid layouts that have height or width set to a percentange.
